-- ITEM: Item tanım tablosu (statik veri)
-- Kaynak: MSSQL dbo.ITEM (PK yok, Num unique olmalı)
CREATE TABLE IF NOT EXISTS item (
    num                 INTEGER         NOT NULL PRIMARY KEY,
    extension           SMALLINT,
    str_name            TEXT,
    description         TEXT,
    item_plus_id        VARCHAR(10),
    item_alteration     SMALLINT,
    item_icon_id1       INTEGER,
    item_icon_id2       INTEGER,
    kind                INTEGER,
    slot                INTEGER,
    race                INTEGER,
    class               INTEGER,
    damage              SMALLINT,
    min_damage          SMALLINT,
    max_damage          SMALLINT,
    delay               SMALLINT,
    range               SMALLINT,
    weight              SMALLINT,
    duration            SMALLINT,
    buy_price           INTEGER,
    sell_price          INTEGER,
    sell_npc_type       INTEGER,
    sell_npc_price      INTEGER,
    ac                  SMALLINT,
    countable           INTEGER,
    effect1             INTEGER,
    effect2             INTEGER,
    req_level           INTEGER,
    req_level_max       INTEGER,
    req_rank            INTEGER,
    req_title           INTEGER,
    req_str             INTEGER,
    req_sta             INTEGER,
    req_dex             INTEGER,
    req_intel           INTEGER,
    req_cha             INTEGER,
    selling_group       INTEGER,
    item_type           INTEGER,
    hitrate             SMALLINT,
    evasionrate         SMALLINT,
    dagger_ac           SMALLINT,
    jamadar_ac          SMALLINT,
    sword_ac            SMALLINT,
    club_ac             SMALLINT,
    axe_ac              SMALLINT,
    spear_ac            SMALLINT,
    bow_ac              SMALLINT,
    fire_damage         INTEGER,
    ice_damage          INTEGER,
    lightning_damage     INTEGER,
    poison_damage       INTEGER,
    hp_drain            INTEGER,
    mp_damage           INTEGER,
    mp_drain            INTEGER,
    mirror_damage       INTEGER,
    droprate            INTEGER,
    str_b               SMALLINT,
    sta_b               SMALLINT,
    dex_b               SMALLINT,
    intel_b             SMALLINT,
    cha_b               SMALLINT,
    max_hp_b            SMALLINT,
    max_mp_b            SMALLINT,
    fire_r              SMALLINT,
    cold_r              SMALLINT,
    lightning_r         SMALLINT,
    magic_r             SMALLINT,
    poison_r            SMALLINT,
    curse_r             SMALLINT,
    item_class          SMALLINT,
    np_buy_price        INTEGER,
    bound               SMALLINT,
    mace_ac             SMALLINT,
    by_grade            SMALLINT,
    drop_notice         SMALLINT,
    upgrade_notice      SMALLINT
);

CREATE INDEX IF NOT EXISTS idx_item_kind ON item (kind);
CREATE INDEX IF NOT EXISTS idx_item_slot ON item (slot);
CREATE INDEX IF NOT EXISTS idx_item_type ON item (item_type);
CREATE INDEX IF NOT EXISTS idx_item_selling_group ON item (selling_group);
