-- Per-GM permission flags (fine-grained access control)
-- Source: MSSQL GAME_MASTER_SETTINGS (38 columns, 3 rows)
CREATE TABLE IF NOT EXISTS game_master_settings (
    char_id                 VARCHAR(21) PRIMARY KEY,
    perm_mute               BOOLEAN NOT NULL DEFAULT true,
    perm_unmute             BOOLEAN NOT NULL DEFAULT true,
    perm_unban              BOOLEAN NOT NULL DEFAULT true,
    perm_ban_permit         BOOLEAN NOT NULL DEFAULT true,
    perm_ban_under          BOOLEAN NOT NULL DEFAULT true,
    perm_ban_days           BOOLEAN NOT NULL DEFAULT true,
    perm_ban_cheating       BOOLEAN NOT NULL DEFAULT true,
    perm_ban_scamming       BOOLEAN NOT NULL DEFAULT true,
    perm_allow_attack       BOOLEAN NOT NULL DEFAULT true,
    perm_disabled_attack    BOOLEAN NOT NULL DEFAULT true,
    perm_np_add             BOOLEAN NOT NULL DEFAULT true,
    perm_exp_add            BOOLEAN NOT NULL DEFAULT true,
    perm_money_add          BOOLEAN NOT NULL DEFAULT true,
    perm_drop_add           BOOLEAN NOT NULL DEFAULT true,
    perm_loyalty_change     BOOLEAN NOT NULL DEFAULT true,
    perm_exp_change         BOOLEAN NOT NULL DEFAULT true,
    perm_money_change       BOOLEAN NOT NULL DEFAULT true,
    perm_give_item          BOOLEAN NOT NULL DEFAULT true,
    perm_give_item_self     BOOLEAN NOT NULL DEFAULT true,
    perm_summon_user        BOOLEAN NOT NULL DEFAULT true,
    perm_tp_on_user         BOOLEAN NOT NULL DEFAULT true,
    perm_zone_change        BOOLEAN NOT NULL DEFAULT true,
    perm_location_change    BOOLEAN NOT NULL DEFAULT true,
    perm_monster_summon     BOOLEAN NOT NULL DEFAULT true,
    perm_npc_summon         BOOLEAN NOT NULL DEFAULT true,
    perm_mon_killed         BOOLEAN NOT NULL DEFAULT true,
    perm_teleport_all_user  BOOLEAN NOT NULL DEFAULT true,
    perm_clan_summon        BOOLEAN NOT NULL DEFAULT true,
    perm_reset_ranking      BOOLEAN NOT NULL DEFAULT true,
    perm_change_event_room  BOOLEAN NOT NULL DEFAULT true,
    perm_war_open           BOOLEAN NOT NULL DEFAULT true,
    perm_war_close          BOOLEAN NOT NULL DEFAULT true,
    perm_captain_election   BOOLEAN NOT NULL DEFAULT true,
    perm_send_prison        BOOLEAN NOT NULL DEFAULT true,
    perm_kc_change          BOOLEAN NOT NULL DEFAULT true,
    perm_reload_tables      BOOLEAN NOT NULL DEFAULT true,
    perm_drop_test          BOOLEAN NOT NULL DEFAULT false
);
