-- USERDATA: Karakter verileri tablosu — login flow için kritik
-- Kaynak: MSSQL dbo.USERDATA (60 kolon)
-- Not: Binary blob kolonları (strItem, strSerial vb.) ayrı tablolara normalize edildi
CREATE TABLE IF NOT EXISTS userdata (
    id                  INTEGER         NOT NULL,
    str_user_id         VARCHAR(21)     NOT NULL PRIMARY KEY,
    nation              SMALLINT        NOT NULL,
    race                SMALLINT        NOT NULL,
    class               SMALLINT        NOT NULL,
    hair_rgb            INTEGER         NOT NULL,
    rank                SMALLINT        NOT NULL DEFAULT 0,
    title               SMALLINT        NOT NULL DEFAULT 0,
    level               SMALLINT        NOT NULL DEFAULT 1,
    rebirth_level       SMALLINT        NOT NULL DEFAULT 0,
    exp                 BIGINT          NOT NULL DEFAULT 0,
    loyalty             INTEGER         NOT NULL DEFAULT 501,
    face                SMALLINT        NOT NULL,
    city                SMALLINT        NOT NULL DEFAULT 0,
    knights             SMALLINT        NOT NULL DEFAULT 0,
    fame                SMALLINT        NOT NULL DEFAULT 0,
    hp                  SMALLINT        NOT NULL DEFAULT 100,
    mp                  SMALLINT        NOT NULL DEFAULT 100,
    sp                  SMALLINT        NOT NULL DEFAULT 100,
    strong              SMALLINT        NOT NULL,
    sta                 SMALLINT        NOT NULL,
    dex                 SMALLINT        NOT NULL,
    intel               SMALLINT        NOT NULL,
    cha                 SMALLINT        NOT NULL,
    reb_str             SMALLINT        NOT NULL DEFAULT 0,
    reb_sta             SMALLINT        NOT NULL DEFAULT 0,
    reb_dex             SMALLINT        NOT NULL DEFAULT 0,
    reb_intel           SMALLINT        NOT NULL DEFAULT 0,
    reb_cha             SMALLINT        NOT NULL DEFAULT 0,
    authority           SMALLINT        NOT NULL DEFAULT 1,
    points              SMALLINT        NOT NULL DEFAULT 0,
    gold                INTEGER         NOT NULL DEFAULT 0,
    zone                SMALLINT        NOT NULL DEFAULT 21,
    bind                SMALLINT        NOT NULL DEFAULT -1,
    px                  INTEGER         NOT NULL DEFAULT 81600,
    pz                  INTEGER         NOT NULL DEFAULT 53200,
    py                  INTEGER         NOT NULL DEFAULT 0,
    dw_time             INTEGER         NOT NULL DEFAULT 0,
    str_skill           VARCHAR(10),
    manner_point        INTEGER         NOT NULL DEFAULT 0,
    loyalty_monthly     INTEGER         NOT NULL DEFAULT 0,
    i_saved_cont        INTEGER         NOT NULL DEFAULT 0,
    dt_create_time      TIMESTAMPTZ     NOT NULL DEFAULT NOW(),
    dt_update_time      TIMESTAMPTZ,
    n_last_login        INTEGER         NOT NULL DEFAULT 0,
    n_donated_np        INTEGER         NOT NULL DEFAULT 0,
    mute_status         INTEGER         NOT NULL DEFAULT 0,
    attack_status       INTEGER         NOT NULL DEFAULT 0,
    tagname             VARCHAR(21)     NOT NULL DEFAULT '-',
    tagname_rgb         INTEGER         NOT NULL DEFAULT 0,
    chicken_status      SMALLINT        NOT NULL DEFAULT 0,
    flash_time          INTEGER         NOT NULL DEFAULT 0,
    flash_count         SMALLINT        NOT NULL DEFAULT 0,
    flash_type          SMALLINT        NOT NULL DEFAULT 0,
    str_memo            VARCHAR(20)
);

CREATE INDEX IF NOT EXISTS idx_userdata_nation ON userdata (nation);
CREATE INDEX IF NOT EXISTS idx_userdata_knights ON userdata (knights);
CREATE INDEX IF NOT EXISTS idx_userdata_zone ON userdata (zone);
CREATE INDEX IF NOT EXISTS idx_userdata_level ON userdata (level);
