-- ============================================================================
-- Migration: v2600 Quest Menu — 731 missing menu text entries
-- Date: 2026-03-25
-- Source: KnightOnlineOriginalClient/Data/Quest_Menu_us.tbl (v2600 client)
--
-- Problem: quest dialog menus reference menu IDs not in quest_menu table
--          → empty menu buttons in NPC dialogs
-- Fix: Add 731 missing quest_menu entries from v2600 TBL
-- ============================================================================

INSERT INTO quest_menu (i_num, str_menu) VALUES (1001, '1¹ø') ON CONFLICT (i_num) DO NOTHING;
INSERT INTO quest_menu (i_num, str_menu) VALUES (1002, '2¹ø') ON CONFLICT (i_num) DO NOTHING;
INSERT INTO quest_menu (i_num, str_menu) VALUES (1003, '3¹ø') ON CONFLICT (i_num) DO NOTHING;
INSERT INTO quest_menu (i_num, str_menu) VALUES (1004, '4¹ø') ON CONFLICT (i_num) DO NOTHING;
INSERT INTO quest_menu (i_num, str_menu) VALUES (1005, '5¹ø') ON CONFLICT (i_num) DO NOTHING;
INSERT INTO quest_menu (i_num, str_menu) VALUES (1006, '6¹ø') ON CONFLICT (i_num) DO NOTHING;
INSERT INTO quest_menu (i_num, str_menu) VALUES (1007, '7¹ø') ON CONFLICT (i_num) DO NOTHING;
INSERT INTO quest_menu (i_num, str_menu) VALUES (1008, '8¹ø') ON CONFLICT (i_num) DO NOTHING;
INSERT INTO quest_menu (i_num, str_menu) VALUES (1009, '9¹ø') ON CONFLICT (i_num) DO NOTHING;
INSERT INTO quest_menu (i_num, str_menu) VALUES (1010, '10¹ø') ON CONFLICT (i_num) DO NOTHING;
INSERT INTO quest_menu (i_num, str_menu) VALUES (40780, 'Register for Stronghold Siege War') ON CONFLICT (i_num) DO NOTHING;
INSERT INTO quest_menu (i_num, str_menu) VALUES (40781, 'Cancel Registration') ON CONFLICT (i_num) DO NOTHING;
INSERT INTO quest_menu (i_num, str_menu) VALUES (40782, 'Participant Clan List') ON CONFLICT (i_num) DO NOTHING;
INSERT INTO quest_menu (i_num, str_menu) VALUES (40783, 'Clan Deathmatch') ON CONFLICT (i_num) DO NOTHING;
INSERT INTO quest_menu (i_num, str_menu) VALUES (40784, 'Stronghold Siege War') ON CONFLICT (i_num) DO NOTHING;
INSERT INTO quest_menu (i_num, str_menu) VALUES (40785, 'Proceed with Nation Point') ON CONFLICT (i_num) DO NOTHING;
INSERT INTO quest_menu (i_num, str_menu) VALUES (40786, 'See Score') ON CONFLICT (i_num) DO NOTHING;
INSERT INTO quest_menu (i_num, str_menu) VALUES (40787, 'Exchange Holy Star') ON CONFLICT (i_num) DO NOTHING;
INSERT INTO quest_menu (i_num, str_menu) VALUES (40788, 'Snow Crystal') ON CONFLICT (i_num) DO NOTHING;
INSERT INTO quest_menu (i_num, str_menu) VALUES (40789, 'Golden Light Snow Knight') ON CONFLICT (i_num) DO NOTHING;
INSERT INTO quest_menu (i_num, str_menu) VALUES (40790, 'Grace of the Moon God') ON CONFLICT (i_num) DO NOTHING;
INSERT INTO quest_menu (i_num, str_menu) VALUES (40791, '1 ct - Warrior of the Moon God') ON CONFLICT (i_num) DO NOTHING;
INSERT INTO quest_menu (i_num, str_menu) VALUES (40792, '5 ct - Legionnaire of the Moon God') ON CONFLICT (i_num) DO NOTHING;
INSERT INTO quest_menu (i_num, str_menu) VALUES (40793, '10 ct - Advent of the Moon God') ON CONFLICT (i_num) DO NOTHING;
INSERT INTO quest_menu (i_num, str_menu) VALUES (40794, '10 ct - Rebirth of the Moon God') ON CONFLICT (i_num) DO NOTHING;
INSERT INTO quest_menu (i_num, str_menu) VALUES (40795, '10 ct - Lion of the Moon God') ON CONFLICT (i_num) DO NOTHING;
INSERT INTO quest_menu (i_num, str_menu) VALUES (40796, '´«¹°ÀÇ Àë½ºÅæ ±³È¯') ON CONFLICT (i_num) DO NOTHING;
INSERT INTO quest_menu (i_num, str_menu) VALUES (40797, '»õÇØÀÇ ±â¿ø ±³È¯') ON CONFLICT (i_num) DO NOTHING;
INSERT INTO quest_menu (i_num, str_menu) VALUES (40798, '5°³ - 2019 ´ë¹Ú±â¿ø ÄªÈ£ ±³È¯') ON CONFLICT (i_num) DO NOTHING;
INSERT INTO quest_menu (i_num, str_menu) VALUES (40799, '1°³ - ·£´ı º¸»ó ±³È¯') ON CONFLICT (i_num) DO NOTHING;
INSERT INTO quest_menu (i_num, str_menu) VALUES (40800, '[Exchange] Soul Gem') ON CONFLICT (i_num) DO NOTHING;
INSERT INTO quest_menu (i_num, str_menu) VALUES (40801, '50 -13th Anniversary Emblem (3 Days)') ON CONFLICT (i_num) DO NOTHING;
INSERT INTO quest_menu (i_num, str_menu) VALUES (40802, '75 - 100x Ibex/Crisis Potions') ON CONFLICT (i_num) DO NOTHING;
INSERT INTO quest_menu (i_num, str_menu) VALUES (40803, '100 -  VIP Vault Key (7 Days)') ON CONFLICT (i_num) DO NOTHING;
INSERT INTO quest_menu (i_num, str_menu) VALUES (40804, '200 - Blue Alencia Wings (15 Days)') ON CONFLICT (i_num) DO NOTHING;
INSERT INTO quest_menu (i_num, str_menu) VALUES (40805, '400 - Lunar Tattoo (15 Days)') ON CONFLICT (i_num) DO NOTHING;
INSERT INTO quest_menu (i_num, str_menu) VALUES (40806, '1000 - Bronze Premium (30 Days)') ON CONFLICT (i_num) DO NOTHING;
INSERT INTO quest_menu (i_num, str_menu) VALUES (40807, '1500°³ - °¡·çÁ¦½º ¹«±â ±³È¯±Ç') ON CONFLICT (i_num) DO NOTHING;
INSERT INTO quest_menu (i_num, str_menu) VALUES (40808, '[Wake up Spirit Nereids]') ON CONFLICT (i_num) DO NOTHING;
INSERT INTO quest_menu (i_num, str_menu) VALUES (40809, 'War Tattoo (30 Days)') ON CONFLICT (i_num) DO NOTHING;
INSERT INTO quest_menu (i_num, str_menu) VALUES (40810, '¼ºÁÖ ÀçÀÓ±â°£ È®ÀÎ') ON CONFLICT (i_num) DO NOTHING;
INSERT INTO quest_menu (i_num, str_menu) VALUES (40811, '·¡´õ º¸»ó ¾ÆÀÌÅÛ ±³È¯') ON CONFLICT (i_num) DO NOTHING;
INSERT INTO quest_menu (i_num, str_menu) VALUES (40812, 'Å©·Î¿ÍÁî ¹æ¾î±¸ +7 ±³È¯') ON CONFLICT (i_num) DO NOTHING;
INSERT INTO quest_menu (i_num, str_menu) VALUES (40813, 'Å©·Î¿ÍÁî ¹æ¾î±¸ +6 ±³È¯') ON CONFLICT (i_num) DO NOTHING;
INSERT INTO quest_menu (i_num, str_menu) VALUES (40814, 'Å©·Î¿ÍÁî ¿ö¸®¾î ¹æ¾î±¸ +7 ') ON CONFLICT (i_num) DO NOTHING;
INSERT INTO quest_menu (i_num, str_menu) VALUES (40815, 'Å©·Î¿ÍÁî ¾î½ê½Å ¹æ¾î±¸ +7 ') ON CONFLICT (i_num) DO NOTHING;
INSERT INTO quest_menu (i_num, str_menu) VALUES (40816, 'Å©·Î¿ÍÁî ¸ŞÀÌÁö ¹æ¾î±¸ +7 ') ON CONFLICT (i_num) DO NOTHING;
INSERT INTO quest_menu (i_num, str_menu) VALUES (40817, 'Å©·Î¿ÍÁî ÇÁ¸®½ºÆ® ¹æ¾î±¸ +7 ') ON CONFLICT (i_num) DO NOTHING;
INSERT INTO quest_menu (i_num, str_menu) VALUES (40818, 'Å©·Î¿ÍÁî Æ÷¸£Åõ ¹æ¾î±¸ +7 ') ON CONFLICT (i_num) DO NOTHING;
INSERT INTO quest_menu (i_num, str_menu) VALUES (40819, 'Å©·Î¿ÍÁî ¿ö¸®¾î ¹æ¾î±¸ +6') ON CONFLICT (i_num) DO NOTHING;
INSERT INTO quest_menu (i_num, str_menu) VALUES (40820, 'Å©·Î¿ÍÁî ¾î½ê½Å ¹æ¾î±¸ +6') ON CONFLICT (i_num) DO NOTHING;
INSERT INTO quest_menu (i_num, str_menu) VALUES (40821, 'Å©·Î¿ÍÁî ¸ŞÀÌÁö ¹æ¾î±¸ +6') ON CONFLICT (i_num) DO NOTHING;
INSERT INTO quest_menu (i_num, str_menu) VALUES (40822, 'Å©·Î¿ÍÁî ÇÁ¸®½ºÆ® ¹æ¾î±¸ +6') ON CONFLICT (i_num) DO NOTHING;
INSERT INTO quest_menu (i_num, str_menu) VALUES (40823, 'Å©·Î¿ÍÁî Æ÷¸£Åõ ¹æ¾î±¸ +6') ON CONFLICT (i_num) DO NOTHING;
INSERT INTO quest_menu (i_num, str_menu) VALUES (40824, '8 - Summon Guard (Defense)') ON CONFLICT (i_num) DO NOTHING;
INSERT INTO quest_menu (i_num, str_menu) VALUES (40825, '8 - Summon Guard (AoE)') ON CONFLICT (i_num) DO NOTHING;
INSERT INTO quest_menu (i_num, str_menu) VALUES (40826, '8 - Summon Guard (Chase)') ON CONFLICT (i_num) DO NOTHING;
INSERT INTO quest_menu (i_num, str_menu) VALUES (40827, '15°³ - ¶óÀÌÆ®´× ¿Àºê ¼îÅ©') ON CONFLICT (i_num) DO NOTHING;
INSERT INTO quest_menu (i_num, str_menu) VALUES (40828, '1 - Splash Hit') ON CONFLICT (i_num) DO NOTHING;
INSERT INTO quest_menu (i_num, str_menu) VALUES (40829, '1 - Splash Attack') ON CONFLICT (i_num) DO NOTHING;
INSERT INTO quest_menu (i_num, str_menu) VALUES (40830, 'Accept Ramadan Emblem') ON CONFLICT (i_num) DO NOTHING;
INSERT INTO quest_menu (i_num, str_menu) VALUES (40831, 'Exchange Dason''s Gift') ON CONFLICT (i_num) DO NOTHING;
INSERT INTO quest_menu (i_num, str_menu) VALUES (40832, 'Glorious Dason''s Gift') ON CONFLICT (i_num) DO NOTHING;
INSERT INTO quest_menu (i_num, str_menu) VALUES (40833, 'Shiny Dason''s Gift') ON CONFLICT (i_num) DO NOTHING;
INSERT INTO quest_menu (i_num, str_menu) VALUES (40834, 'Old Dason''s Gift') ON CONFLICT (i_num) DO NOTHING;
INSERT INTO quest_menu (i_num, str_menu) VALUES (40835, '¸¸¿ùÀÇ Â÷¿ø »óÀÚ ±³È¯') ON CONFLICT (i_num) DO NOTHING;
INSERT INTO quest_menu (i_num, str_menu) VALUES (40836, '±İºû ¸¸¿ùÀÇ Â÷¿ø »óÀÚ') ON CONFLICT (i_num) DO NOTHING;
INSERT INTO quest_menu (i_num, str_menu) VALUES (40837, '¸¸¿ùÀÇ Â÷¿ø »óÀÚ') ON CONFLICT (i_num) DO NOTHING;
INSERT INTO quest_menu (i_num, str_menu) VALUES (40838, 'È¯»ı ¾öºí·³ ±³È¯') ON CONFLICT (i_num) DO NOTHING;
INSERT INTO quest_menu (i_num, str_menu) VALUES (40839, '1st Clan House') ON CONFLICT (i_num) DO NOTHING;
INSERT INTO quest_menu (i_num, str_menu) VALUES (40840, '2nd Clan House') ON CONFLICT (i_num) DO NOTHING;
INSERT INTO quest_menu (i_num, str_menu) VALUES (40841, '3rd Clan House') ON CONFLICT (i_num) DO NOTHING;
INSERT INTO quest_menu (i_num, str_menu) VALUES (40842, '[Ãà±¸º¹ Áö±Ş ¹Ş±â]') ON CONFLICT (i_num) DO NOTHING;
INSERT INTO quest_menu (i_num, str_menu) VALUES (40843, '250 - ¸¸¿ùÀÇ Â÷¿ø »óÀÚ') ON CONFLICT (i_num) DO NOTHING;
INSERT INTO quest_menu (i_num, str_menu) VALUES (40844, '300 - ¸¶¹ıÀÇ °¡¹æ 7ÀÏ±Ç') ON CONFLICT (i_num) DO NOTHING;
INSERT INTO quest_menu (i_num, str_menu) VALUES (40845, '400 - ±İºû ¸¸¿ùÀÇ Â÷¿ø »óÀÚ') ON CONFLICT (i_num) DO NOTHING;
INSERT INTO quest_menu (i_num, str_menu) VALUES (40846, '500 - ´Ş¿¡ ½ÅÀÇ °¡È£') ON CONFLICT (i_num) DO NOTHING;
INSERT INTO quest_menu (i_num, str_menu) VALUES (40847, '700 - Åä³¢ ÆÖ º¯½Å ÁÖ¹®¼­') ON CONFLICT (i_num) DO NOTHING;
INSERT INTO quest_menu (i_num, str_menu) VALUES (40848, '1000 - ´ŞÀÇ Å¸Åõ 15ÀÏ±Ç') ON CONFLICT (i_num) DO NOTHING;
INSERT INTO quest_menu (i_num, str_menu) VALUES (40849, 'Blessing of Solar God') ON CONFLICT (i_num) DO NOTHING;
INSERT INTO quest_menu (i_num, str_menu) VALUES (40850, 'Receive 14th Anniversary Reward') ON CONFLICT (i_num) DO NOTHING;
INSERT INTO quest_menu (i_num, str_menu) VALUES (40851, '50 - Event Emblem(3 Days)') ON CONFLICT (i_num) DO NOTHING;
INSERT INTO quest_menu (i_num, str_menu) VALUES (40852, '15 - Crisis/Ibexs Transformation Scroll') ON CONFLICT (i_num) DO NOTHING;
INSERT INTO quest_menu (i_num, str_menu) VALUES (40853, '100 - VIP Vault Key (7 Days)') ON CONFLICT (i_num) DO NOTHING;
INSERT INTO quest_menu (i_num, str_menu) VALUES (40854, '300 - Solar Pendant') ON CONFLICT (i_num) DO NOTHING;
INSERT INTO quest_menu (i_num, str_menu) VALUES (40855, '100 - Pathos Glove (7 Days)') ON CONFLICT (i_num) DO NOTHING;
INSERT INTO quest_menu (i_num, str_menu) VALUES (40856, '150 - Magic hammer') ON CONFLICT (i_num) DO NOTHING;
INSERT INTO quest_menu (i_num, str_menu) VALUES (40857, '900 - <Solar Messenger> Achievement') ON CONFLICT (i_num) DO NOTHING;
INSERT INTO quest_menu (i_num, str_menu) VALUES (40858, '500 - Switching Premium (1 Day)') ON CONFLICT (i_num) DO NOTHING;
INSERT INTO quest_menu (i_num, str_menu) VALUES (40859, '[Exchange] 14th Anniversary Emblem') ON CONFLICT (i_num) DO NOTHING;
INSERT INTO quest_menu (i_num, str_menu) VALUES (40860, '14th Anniversary Emblem (1 Day)') ON CONFLICT (i_num) DO NOTHING;
INSERT INTO quest_menu (i_num, str_menu) VALUES (40861, '14th Anniversary Emblem (3 Days)') ON CONFLICT (i_num) DO NOTHING;
INSERT INTO quest_menu (i_num, str_menu) VALUES (40862, '14th Anniversary Emblem (7 Days)') ON CONFLICT (i_num) DO NOTHING;
INSERT INTO quest_menu (i_num, str_menu) VALUES (40863, '14th Anniversary Emblem (15 Days)') ON CONFLICT (i_num) DO NOTHING;
INSERT INTO quest_menu (i_num, str_menu) VALUES (40864, '14th Anniversary Emblem (30 Days)') ON CONFLICT (i_num) DO NOTHING;
INSERT INTO quest_menu (i_num, str_menu) VALUES (40865, '[Exchange] 14th Anniversary Replica Emblem') ON CONFLICT (i_num) DO NOTHING;
INSERT INTO quest_menu (i_num, str_menu) VALUES (40866, '[Exchange] Holy Knight Armor') ON CONFLICT (i_num) DO NOTHING;
INSERT INTO quest_menu (i_num, str_menu) VALUES (40868, 'Solar Tattoo (1 Days)') ON CONFLICT (i_num) DO NOTHING;
INSERT INTO quest_menu (i_num, str_menu) VALUES (40869, 'Move to Moradon') ON CONFLICT (i_num) DO NOTHING;
INSERT INTO quest_menu (i_num, str_menu) VALUES (40870, 'Receive SSW Reward') ON CONFLICT (i_num) DO NOTHING;
INSERT INTO quest_menu (i_num, str_menu) VALUES (40871, '[ÀÌº¥Æ®] ÀüÀå ¿µ¿õÀÇ ³¯°³ ±³È¯') ON CONFLICT (i_num) DO NOTHING;
INSERT INTO quest_menu (i_num, str_menu) VALUES (40872, '[ÀÌº¥Æ®] ÀüÀå ¿µ¿õÀÇ ³¯°³ ±³È¯ (30ÀÏ)') ON CONFLICT (i_num) DO NOTHING;
INSERT INTO quest_menu (i_num, str_menu) VALUES (40873, 'Exchange [Pandora''s Box]') ON CONFLICT (i_num) DO NOTHING;
INSERT INTO quest_menu (i_num, str_menu) VALUES (40874, 'Exchange ''LIKE'' Emblem') ON CONFLICT (i_num) DO NOTHING;
INSERT INTO quest_menu (i_num, str_menu) VALUES (40875, '[Pandora''s Box]Exchanging items') ON CONFLICT (i_num) DO NOTHING;
INSERT INTO quest_menu (i_num, str_menu) VALUES (40876, '[Gold Dragon Egg] Juriad Jewel Box') ON CONFLICT (i_num) DO NOTHING;
INSERT INTO quest_menu (i_num, str_menu) VALUES (40877, '[Gold Dragon Egg] Accessories Box') ON CONFLICT (i_num) DO NOTHING;
INSERT INTO quest_menu (i_num, str_menu) VALUES (40878, '[Gold Dragon Egg] Bifrost Box') ON CONFLICT (i_num) DO NOTHING;
INSERT INTO quest_menu (i_num, str_menu) VALUES (40879, '[Gold Dragon Egg] 7th Armor Package') ON CONFLICT (i_num) DO NOTHING;
INSERT INTO quest_menu (i_num, str_menu) VALUES (40880, '[Gold Dragon Egg] Guardian Exchange Coupon') ON CONFLICT (i_num) DO NOTHING;
INSERT INTO quest_menu (i_num, str_menu) VALUES (40881, '[Gold Dragon Egg] Magpie Mama transformation vouchers') ON CONFLICT (i_num) DO NOTHING;
INSERT INTO quest_menu (i_num, str_menu) VALUES (40882, '[Gold Dragon Egg] Exchanging items') ON CONFLICT (i_num) DO NOTHING;
INSERT INTO quest_menu (i_num, str_menu) VALUES (40883, '[Gold Dragon Egg] Battlefield Hero''s Wing Exchange Coupon') ON CONFLICT (i_num) DO NOTHING;
INSERT INTO quest_menu (i_num, str_menu) VALUES (40884, '[Gold Dragon Egg] Wing weapons case') ON CONFLICT (i_num) DO NOTHING;
INSERT INTO quest_menu (i_num, str_menu) VALUES (40885, '[Gold Dragon Egg]Special Accessories Box') ON CONFLICT (i_num) DO NOTHING;
INSERT INTO quest_menu (i_num, str_menu) VALUES (40886, '[Gold Dragon Egg]+4 Rosetta Armor Exchange') ON CONFLICT (i_num) DO NOTHING;
INSERT INTO quest_menu (i_num, str_menu) VALUES (40887, '[Exchange] Minerva Costumes') ON CONFLICT (i_num) DO NOTHING;
INSERT INTO quest_menu (i_num, str_menu) VALUES (40888, 'Anything in the Pandora''s Box!') ON CONFLICT (i_num) DO NOTHING;
INSERT INTO quest_menu (i_num, str_menu) VALUES (40889, 'Food Ingredient Thief') ON CONFLICT (i_num) DO NOTHING;
INSERT INTO quest_menu (i_num, str_menu) VALUES (40890, 'Thanksgiving Box') ON CONFLICT (i_num) DO NOTHING;
INSERT INTO quest_menu (i_num, str_menu) VALUES (40891, 'Exchange [Golden Yut]') ON CONFLICT (i_num) DO NOTHING;
INSERT INTO quest_menu (i_num, str_menu) VALUES (40892, 'Exchange 9 [Golden Yut]') ON CONFLICT (i_num) DO NOTHING;
INSERT INTO quest_menu (i_num, str_menu) VALUES (40893, 'Exchange 40 [Golden Yut] (Daily)') ON CONFLICT (i_num) DO NOTHING;
INSERT INTO quest_menu (i_num, str_menu) VALUES (40894, '10 - 5 Weapon Enchant Scroll') ON CONFLICT (i_num) DO NOTHING;
INSERT INTO quest_menu (i_num, str_menu) VALUES (40895, '10 - 5 Armor Enchant Scroll') ON CONFLICT (i_num) DO NOTHING;
INSERT INTO quest_menu (i_num, str_menu) VALUES (40896, '30 - Genie Hammer') ON CONFLICT (i_num) DO NOTHING;
INSERT INTO quest_menu (i_num, str_menu) VALUES (40897, '70 - Magic Bag (7 Days)') ON CONFLICT (i_num) DO NOTHING;
INSERT INTO quest_menu (i_num, str_menu) VALUES (40898, '100 - 1 Lunar Rabbit Mortar Piece') ON CONFLICT (i_num) DO NOTHING;
INSERT INTO quest_menu (i_num, str_menu) VALUES (40899, '150 - Oreads (3 Days)') ON CONFLICT (i_num) DO NOTHING;
INSERT INTO quest_menu (i_num, str_menu) VALUES (40900, '200 - Full Moon Emblem 15 Days') ON CONFLICT (i_num) DO NOTHING;
INSERT INTO quest_menu (i_num, str_menu) VALUES (40901, '300 - Lunar Tattoo (30 Days)') ON CONFLICT (i_num) DO NOTHING;
INSERT INTO quest_menu (i_num, str_menu) VALUES (40902, 'Empires Reward Voucher') ON CONFLICT (i_num) DO NOTHING;
INSERT INTO quest_menu (i_num, str_menu) VALUES (40903, 'Empires Token') ON CONFLICT (i_num) DO NOTHING;
INSERT INTO quest_menu (i_num, str_menu) VALUES (40904, '5 - Amor & Weapon Enchant Scroll') ON CONFLICT (i_num) DO NOTHING;
INSERT INTO quest_menu (i_num, str_menu) VALUES (40905, '10 - Monster Stone') ON CONFLICT (i_num) DO NOTHING;
INSERT INTO quest_menu (i_num, str_menu) VALUES (40906, '20 -  VIP Vault Key (7 Days)') ON CONFLICT (i_num) DO NOTHING;
INSERT INTO quest_menu (i_num, str_menu) VALUES (40907, '35 - Golden Lunar Box') ON CONFLICT (i_num) DO NOTHING;
INSERT INTO quest_menu (i_num, str_menu) VALUES (40908, '50 - Battle Hero Wings (7 Days)') ON CONFLICT (i_num) DO NOTHING;
INSERT INTO quest_menu (i_num, str_menu) VALUES (40909, '70 - [Hero of Empires] Title Voucher') ON CONFLICT (i_num) DO NOTHING;
INSERT INTO quest_menu (i_num, str_menu) VALUES (40910, '90 - Lunar Tattoo (15 Days) Exchange') ON CONFLICT (i_num) DO NOTHING;
INSERT INTO quest_menu (i_num, str_menu) VALUES (40911, '[Empires Champion Emblem] Voucher ') ON CONFLICT (i_num) DO NOTHING;
INSERT INTO quest_menu (i_num, str_menu) VALUES (40912, '[Empires Champion Emblem] Voucher (1 Day)') ON CONFLICT (i_num) DO NOTHING;
INSERT INTO quest_menu (i_num, str_menu) VALUES (40913, '[Empires Champion Emblem] Voucher (3 Days)') ON CONFLICT (i_num) DO NOTHING;
INSERT INTO quest_menu (i_num, str_menu) VALUES (40914, '[Empires Champion Emblem] Voucher (7 Days)') ON CONFLICT (i_num) DO NOTHING;
INSERT INTO quest_menu (i_num, str_menu) VALUES (40915, '[Empires Champion Emblem] Voucher (15 Days)') ON CONFLICT (i_num) DO NOTHING;
INSERT INTO quest_menu (i_num, str_menu) VALUES (40916, '[Empires Champion Emblem] Voucher (30 Days)') ON CONFLICT (i_num) DO NOTHING;
INSERT INTO quest_menu (i_num, str_menu) VALUES (40917, '[Hero of Empires] Title Voucher') ON CONFLICT (i_num) DO NOTHING;
INSERT INTO quest_menu (i_num, str_menu) VALUES (40918, 'War Horse') ON CONFLICT (i_num) DO NOTHING;
INSERT INTO quest_menu (i_num, str_menu) VALUES (40919, 'Swift Horse') ON CONFLICT (i_num) DO NOTHING;
INSERT INTO quest_menu (i_num, str_menu) VALUES (40920, 'Donkey') ON CONFLICT (i_num) DO NOTHING;
INSERT INTO quest_menu (i_num, str_menu) VALUES (40921, 'ÁÖ³â ¿¥ºí·³ ±³È¯') ON CONFLICT (i_num) DO NOTHING;
INSERT INTO quest_menu (i_num, str_menu) VALUES (40922, '[Full Moon Emblem]') ON CONFLICT (i_num) DO NOTHING;
INSERT INTO quest_menu (i_num, str_menu) VALUES (40923, '[Full Moon Emblem] 1 Day') ON CONFLICT (i_num) DO NOTHING;
INSERT INTO quest_menu (i_num, str_menu) VALUES (40924, '[Full Moon Emblem] 3 Days') ON CONFLICT (i_num) DO NOTHING;
INSERT INTO quest_menu (i_num, str_menu) VALUES (40925, '[Full Moon Emblem] 7 Days') ON CONFLICT (i_num) DO NOTHING;
INSERT INTO quest_menu (i_num, str_menu) VALUES (40926, '[Full Moon Emblem] 15 Days') ON CONFLICT (i_num) DO NOTHING;
INSERT INTO quest_menu (i_num, str_menu) VALUES (40927, '[Full Moon Emblem] 30 Days') ON CONFLICT (i_num) DO NOTHING;
INSERT INTO quest_menu (i_num, str_menu) VALUES (40928, '[Full Moon Emblem Replica]') ON CONFLICT (i_num) DO NOTHING;
INSERT INTO quest_menu (i_num, str_menu) VALUES (40929, 'Warrior & Portu') ON CONFLICT (i_num) DO NOTHING;
INSERT INTO quest_menu (i_num, str_menu) VALUES (40930, 'Rogue') ON CONFLICT (i_num) DO NOTHING;
INSERT INTO quest_menu (i_num, str_menu) VALUES (40931, 'Mage') ON CONFLICT (i_num) DO NOTHING;
INSERT INTO quest_menu (i_num, str_menu) VALUES (40932, 'Priest') ON CONFLICT (i_num) DO NOTHING;
INSERT INTO quest_menu (i_num, str_menu) VALUES (40933, 'Shard') ON CONFLICT (i_num) DO NOTHING;
INSERT INTO quest_menu (i_num, str_menu) VALUES (40934, 'Iron Bow') ON CONFLICT (i_num) DO NOTHING;
INSERT INTO quest_menu (i_num, str_menu) VALUES (40935, 'Lightning') ON CONFLICT (i_num) DO NOTHING;
INSERT INTO quest_menu (i_num, str_menu) VALUES (40936, 'Ice') ON CONFLICT (i_num) DO NOTHING;
INSERT INTO quest_menu (i_num, str_menu) VALUES (40937, 'Fire') ON CONFLICT (i_num) DO NOTHING;
INSERT INTO quest_menu (i_num, str_menu) VALUES (40938, 'Nimbus Tattoo (1 Day)') ON CONFLICT (i_num) DO NOTHING;
INSERT INTO quest_menu (i_num, str_menu) VALUES (40939, 'Lunar Tattoo (1 Day)') ON CONFLICT (i_num) DO NOTHING;
INSERT INTO quest_menu (i_num, str_menu) VALUES (40940, 'Fort Conquest Tutorial Zone') ON CONFLICT (i_num) DO NOTHING;
INSERT INTO quest_menu (i_num, str_menu) VALUES (40941, '10,000,000 Noah') ON CONFLICT (i_num) DO NOTHING;
INSERT INTO quest_menu (i_num, str_menu) VALUES (40942, '50,000,000 Noah') ON CONFLICT (i_num) DO NOTHING;
INSERT INTO quest_menu (i_num, str_menu) VALUES (40943, '100,000,000 Noah') ON CONFLICT (i_num) DO NOTHING;
INSERT INTO quest_menu (i_num, str_menu) VALUES (40944, 'FaceScan') ON CONFLICT (i_num) DO NOTHING;
INSERT INTO quest_menu (i_num, str_menu) VALUES (40945, 'What is FaceScan?') ON CONFLICT (i_num) DO NOTHING;
INSERT INTO quest_menu (i_num, str_menu) VALUES (40946, '½Å³âÀÇ ±â¿î ±³È¯') ON CONFLICT (i_num) DO NOTHING;
INSERT INTO quest_menu (i_num, str_menu) VALUES (40947, '¿À¿°µÈ ¼º¼ö 1°³') ON CONFLICT (i_num) DO NOTHING;
INSERT INTO quest_menu (i_num, str_menu) VALUES (40948, 'ÆÄÅä½ºÀÇ Àå°© Áõ¸í¼­(1ÀÏ)') ON CONFLICT (i_num) DO NOTHING;
INSERT INTO quest_menu (i_num, str_menu) VALUES (40949, '80% ºÎÈ° ÁÖ¹®¼­') ON CONFLICT (i_num) DO NOTHING;
INSERT INTO quest_menu (i_num, str_menu) VALUES (40950, '¿À¿°µÈ ¼º¼ö 11°³') ON CONFLICT (i_num) DO NOTHING;
INSERT INTO quest_menu (i_num, str_menu) VALUES (40951, '´ŞÀÇ Å¸Åõ ±³È¯±Ç(30ÀÏ)') ON CONFLICT (i_num) DO NOTHING;
INSERT INTO quest_menu (i_num, str_menu) VALUES (40952, 'ÀüÀå ¿µ¿õÀÇ ³¯°³(30ÀÏ)') ON CONFLICT (i_num) DO NOTHING;
INSERT INTO quest_menu (i_num, str_menu) VALUES (40953, 'ÀüÀåÀÇ °øÆ÷(ÄªÈ£)') ON CONFLICT (i_num) DO NOTHING;
INSERT INTO quest_menu (i_num, str_menu) VALUES (40954, 'ÄÚÀÎ ±³È¯') ON CONFLICT (i_num) DO NOTHING;
INSERT INTO quest_menu (i_num, str_menu) VALUES (40955, '[¸àÅä ¿¥ºí·³] ±³È¯') ON CONFLICT (i_num) DO NOTHING;
INSERT INTO quest_menu (i_num, str_menu) VALUES (40956, '[¸àÅä ¿¥ºí·³] ±³È¯±Ç(1ÀÏ)') ON CONFLICT (i_num) DO NOTHING;
INSERT INTO quest_menu (i_num, str_menu) VALUES (40957, '[¸àÅä ¿¥ºí·³] ±³È¯±Ç(3ÀÏ)') ON CONFLICT (i_num) DO NOTHING;
INSERT INTO quest_menu (i_num, str_menu) VALUES (40958, '[¸àÅä ¿¥ºí·³] ±³È¯±Ç(7ÀÏ)') ON CONFLICT (i_num) DO NOTHING;
INSERT INTO quest_menu (i_num, str_menu) VALUES (40959, '[¸àÅä ¿¥ºí·³] ±³È¯±Ç(15ÀÏ)') ON CONFLICT (i_num) DO NOTHING;
INSERT INTO quest_menu (i_num, str_menu) VALUES (40960, '[¸àÅä ¿¥ºí·³] ±³È¯±Ç(30ÀÏ)') ON CONFLICT (i_num) DO NOTHING;
INSERT INTO quest_menu (i_num, str_menu) VALUES (40961, '5°³ - 2019 ´ë¹Ú±â¿ø ÄªÈ£ ±³È¯') ON CONFLICT (i_num) DO NOTHING;
INSERT INTO quest_menu (i_num, str_menu) VALUES (40962, '°¨»çÇÕ´Ï´Ù. ') ON CONFLICT (i_num) DO NOTHING;
INSERT INTO quest_menu (i_num, str_menu) VALUES (40963, '¹ß·»Å¸ÀÎ µ¥ÀÌ') ON CONFLICT (i_num) DO NOTHING;
INSERT INTO quest_menu (i_num, str_menu) VALUES (40964, '40 - Lunar Tattoo (3Days)') ON CONFLICT (i_num) DO NOTHING;
INSERT INTO quest_menu (i_num, str_menu) VALUES (40965, '7°³ - º¸¸§´Ş ¿¥ºí·³(3ÀÏ)') ON CONFLICT (i_num) DO NOTHING;
INSERT INTO quest_menu (i_num, str_menu) VALUES (40966, '50°³ - º°ÀÇ Å¸Åõ(1ÀÏ)') ON CONFLICT (i_num) DO NOTHING;
INSERT INTO quest_menu (i_num, str_menu) VALUES (40967, '400°³ - Åä³¢ Æê º¯½Å ÁÖ¹®¼­') ON CONFLICT (i_num) DO NOTHING;
INSERT INTO quest_menu (i_num, str_menu) VALUES (40968, '[Event Emblem] Exchange') ON CONFLICT (i_num) DO NOTHING;
INSERT INTO quest_menu (i_num, str_menu) VALUES (40969, '[Event Emblem] (1day)') ON CONFLICT (i_num) DO NOTHING;
INSERT INTO quest_menu (i_num, str_menu) VALUES (40970, '[Event Emblem] (3day)') ON CONFLICT (i_num) DO NOTHING;
INSERT INTO quest_menu (i_num, str_menu) VALUES (40971, '[Event Emblem] (7day)') ON CONFLICT (i_num) DO NOTHING;
INSERT INTO quest_menu (i_num, str_menu) VALUES (40972, '[Event Emblem] (15day)') ON CONFLICT (i_num) DO NOTHING;
INSERT INTO quest_menu (i_num, str_menu) VALUES (40973, '[Event Emblem] (30day)') ON CONFLICT (i_num) DO NOTHING;
INSERT INTO quest_menu (i_num, str_menu) VALUES (40974, 'Ãàº¹ º¸¹°»óÀÚ ±³È¯') ON CONFLICT (i_num) DO NOTHING;
INSERT INTO quest_menu (i_num, str_menu) VALUES (40975, 'Ãàº¹ º¸¹°»óÀÚ ±³È¯') ON CONFLICT (i_num) DO NOTHING;
INSERT INTO quest_menu (i_num, str_menu) VALUES (40976, '[¾î¸°ÀÌ³¯ ÀÌº¥Æ®] Äµµğ »çÁ¦¿ë ¸ŞÀÌ½º(+1) ¹Ş±â') ON CONFLICT (i_num) DO NOTHING;
INSERT INTO quest_menu (i_num, str_menu) VALUES (40977, 'Äµµğ »çÁ¦¿ë ¸ŞÀÌ½º(+3)') ON CONFLICT (i_num) DO NOTHING;
INSERT INTO quest_menu (i_num, str_menu) VALUES (40978, 'Äµµğ »çÁ¦¿ë ¸ŞÀÌ½º(+4)') ON CONFLICT (i_num) DO NOTHING;
INSERT INTO quest_menu (i_num, str_menu) VALUES (40979, 'Äµµğ »çÁ¦¿ë ¸ŞÀÌ½º(+5)') ON CONFLICT (i_num) DO NOTHING;
INSERT INTO quest_menu (i_num, str_menu) VALUES (40980, 'Äµµğ »çÁ¦¿ë ¸ŞÀÌ½º(+6)') ON CONFLICT (i_num) DO NOTHING;
INSERT INTO quest_menu (i_num, str_menu) VALUES (40981, 'Äµµğ »çÁ¦¿ë ¸ŞÀÌ½º(+7)') ON CONFLICT (i_num) DO NOTHING;
INSERT INTO quest_menu (i_num, str_menu) VALUES (40982, 'Äµµğ »çÁ¦¿ë ¸ŞÀÌ½º(+8)') ON CONFLICT (i_num) DO NOTHING;
INSERT INTO quest_menu (i_num, str_menu) VALUES (40983, 'Äµµğ »çÁ¦¿ë ¸ŞÀÌ½º(+9)') ON CONFLICT (i_num) DO NOTHING;
INSERT INTO quest_menu (i_num, str_menu) VALUES (40984, 'Äµµğ »çÁ¦¿ë ¸ŞÀÌ½º(+10)') ON CONFLICT (i_num) DO NOTHING;
INSERT INTO quest_menu (i_num, str_menu) VALUES (40985, 'Äµµğ »çÁ¦¿ë ¸ŞÀÌ½º ±³È¯') ON CONFLICT (i_num) DO NOTHING;
INSERT INTO quest_menu (i_num, str_menu) VALUES (40986, 'Äµµğ »ç¼¼¿ë ¸ŞÀÌ½º(+1) ±¸¸Å (50¸¸ ³ë¾Æ ¼Ò¸ğ)') ON CONFLICT (i_num) DO NOTHING;
INSERT INTO quest_menu (i_num, str_menu) VALUES (40987, 'Redistributions') ON CONFLICT (i_num) DO NOTHING;
INSERT INTO quest_menu (i_num, str_menu) VALUES (40988, 'Repurchase Sold or Destroyed items') ON CONFLICT (i_num) DO NOTHING;
INSERT INTO quest_menu (i_num, str_menu) VALUES (40989, '15th Anniversary Event') ON CONFLICT (i_num) DO NOTHING;
INSERT INTO quest_menu (i_num, str_menu) VALUES (40990, 'Dragon''s Gift') ON CONFLICT (i_num) DO NOTHING;
INSERT INTO quest_menu (i_num, str_menu) VALUES (40991, '21th Anniversary Appreciation') ON CONFLICT (i_num) DO NOTHING;
INSERT INTO quest_menu (i_num, str_menu) VALUES (40992, 'Hit and Miss Festival Begins') ON CONFLICT (i_num) DO NOTHING;
INSERT INTO quest_menu (i_num, str_menu) VALUES (40993, 'Hit and Miss Quest') ON CONFLICT (i_num) DO NOTHING;
INSERT INTO quest_menu (i_num, str_menu) VALUES (40994, 'Exchange [Solar Light]') ON CONFLICT (i_num) DO NOTHING;
INSERT INTO quest_menu (i_num, str_menu) VALUES (40995, '[Daily] Green Mithril Piece') ON CONFLICT (i_num) DO NOTHING;
INSERT INTO quest_menu (i_num, str_menu) VALUES (40996, '[Exchange] Green Mithril Piece') ON CONFLICT (i_num) DO NOTHING;
INSERT INTO quest_menu (i_num, str_menu) VALUES (44997, '°æÃà º¸¹°»óÀÚ') ON CONFLICT (i_num) DO NOTHING;
INSERT INTO quest_menu (i_num, str_menu) VALUES (44998, '°æÃà º¸¹°»óÀÚ5°³¹­À½') ON CONFLICT (i_num) DO NOTHING;
INSERT INTO quest_menu (i_num, str_menu) VALUES (44999, '´Ü¿À ÀÌº¥Æ® º¸»ó ±³È¯') ON CONFLICT (i_num) DO NOTHING;
INSERT INTO quest_menu (i_num, str_menu) VALUES (45000, 'Anniversary Chest') ON CONFLICT (i_num) DO NOTHING;
INSERT INTO quest_menu (i_num, str_menu) VALUES (45001, '[Exchange] 15th Anniversary Emblem') ON CONFLICT (i_num) DO NOTHING;
INSERT INTO quest_menu (i_num, str_menu) VALUES (45002, '15th Anniversary Emblem (1 Day)') ON CONFLICT (i_num) DO NOTHING;
INSERT INTO quest_menu (i_num, str_menu) VALUES (45003, '15th Anniversary Emblem (3 Days)') ON CONFLICT (i_num) DO NOTHING;
INSERT INTO quest_menu (i_num, str_menu) VALUES (45004, '15th Anniversary Emblem (7 Days)') ON CONFLICT (i_num) DO NOTHING;
INSERT INTO quest_menu (i_num, str_menu) VALUES (45005, '15th Anniversary Emblem (15 Days)') ON CONFLICT (i_num) DO NOTHING;
INSERT INTO quest_menu (i_num, str_menu) VALUES (45006, '15th Anniversary Emblem (30 Days)') ON CONFLICT (i_num) DO NOTHING;
INSERT INTO quest_menu (i_num, str_menu) VALUES (45007, '17ÁÖ³â ÇÑÁ¤ Çà¿î »óÀÚ & Çà¿î1~8') ON CONFLICT (i_num) DO NOTHING;
INSERT INTO quest_menu (i_num, str_menu) VALUES (45008, '17ÁÖ³â ÇÑÁ¤ Çà¿î »óÀÚ') ON CONFLICT (i_num) DO NOTHING;
INSERT INTO quest_menu (i_num, str_menu) VALUES (45009, 'Çà¿î»óÀÚ1') ON CONFLICT (i_num) DO NOTHING;
INSERT INTO quest_menu (i_num, str_menu) VALUES (45010, 'Çà¿î»óÀÚ2') ON CONFLICT (i_num) DO NOTHING;
INSERT INTO quest_menu (i_num, str_menu) VALUES (45011, 'Çà¿î»óÀÚ3') ON CONFLICT (i_num) DO NOTHING;
INSERT INTO quest_menu (i_num, str_menu) VALUES (45012, 'Çà¿î»óÀÚ4') ON CONFLICT (i_num) DO NOTHING;
INSERT INTO quest_menu (i_num, str_menu) VALUES (45013, 'Çà¿î»óÀÚ5') ON CONFLICT (i_num) DO NOTHING;
INSERT INTO quest_menu (i_num, str_menu) VALUES (45014, 'Çà¿î»óÀÚ6') ON CONFLICT (i_num) DO NOTHING;
INSERT INTO quest_menu (i_num, str_menu) VALUES (45015, 'Çà¿î»óÀÚ7') ON CONFLICT (i_num) DO NOTHING;
INSERT INTO quest_menu (i_num, str_menu) VALUES (45016, 'Çà¿î»óÀÚ8') ON CONFLICT (i_num) DO NOTHING;
INSERT INTO quest_menu (i_num, str_menu) VALUES (45017, 'ÅÂ¾çÀÇ Å¸Åõ (15ÀÏ) ±³È¯') ON CONFLICT (i_num) DO NOTHING;
INSERT INTO quest_menu (i_num, str_menu) VALUES (45018, 'Çà¿î 1~8 »óÀÚ') ON CONFLICT (i_num) DO NOTHING;
INSERT INTO quest_menu (i_num, str_menu) VALUES (45019, 'Äµµğ ¾ç¼Õ°Ë(1+) ±¸¸Å') ON CONFLICT (i_num) DO NOTHING;
INSERT INTO quest_menu (i_num, str_menu) VALUES (45020, 'Äµµğ ¾ç¼Õ °Ë (+1) ¹Ş±â') ON CONFLICT (i_num) DO NOTHING;
INSERT INTO quest_menu (i_num, str_menu) VALUES (45021, 'ÄªÈ£ ±³È¯') ON CONFLICT (i_num) DO NOTHING;
INSERT INTO quest_menu (i_num, str_menu) VALUES (45022, '´Ù Âø°¢ÀÌ¾ß ÄªÈ£ ±³È¯') ON CONFLICT (i_num) DO NOTHING;
INSERT INTO quest_menu (i_num, str_menu) VALUES (45023, 'Collect Pine Needles!') ON CONFLICT (i_num) DO NOTHING;
INSERT INTO quest_menu (i_num, str_menu) VALUES (45024, 'Weapon Enchant Scroll - 10') ON CONFLICT (i_num) DO NOTHING;
INSERT INTO quest_menu (i_num, str_menu) VALUES (45025, 'Armor Enchant Scroll - 10') ON CONFLICT (i_num) DO NOTHING;
INSERT INTO quest_menu (i_num, str_menu) VALUES (45026, '30 Duration Item') ON CONFLICT (i_num) DO NOTHING;
INSERT INTO quest_menu (i_num, str_menu) VALUES (45027, '7 Day Magic Bag - 70') ON CONFLICT (i_num) DO NOTHING;
INSERT INTO quest_menu (i_num, str_menu) VALUES (45028, 'Moon Rabbit''s Mortar Piece - 100') ON CONFLICT (i_num) DO NOTHING;
INSERT INTO quest_menu (i_num, str_menu) VALUES (45029, '3 Day Oryads - 150') ON CONFLICT (i_num) DO NOTHING;
INSERT INTO quest_menu (i_num, str_menu) VALUES (45030, 'Full Moon Emblem (15day) - 200') ON CONFLICT (i_num) DO NOTHING;
INSERT INTO quest_menu (i_num, str_menu) VALUES (45031, 'Moon Tattoo (30 days) - 300') ON CONFLICT (i_num) DO NOTHING;
INSERT INTO quest_menu (i_num, str_menu) VALUES (45032, 'Rice Cake (small) - 100 ') ON CONFLICT (i_num) DO NOTHING;
INSERT INTO quest_menu (i_num, str_menu) VALUES (45033, 'Hey Friend! How long has it been?') ON CONFLICT (i_num) DO NOTHING;
INSERT INTO quest_menu (i_num, str_menu) VALUES (45034, 'Carrot Carrot Carrot Exchange') ON CONFLICT (i_num) DO NOTHING;
INSERT INTO quest_menu (i_num, str_menu) VALUES (45035, 'Will be Summoned') ON CONFLICT (i_num) DO NOTHING;
INSERT INTO quest_menu (i_num, str_menu) VALUES (45036, 'All monsters have been caught') ON CONFLICT (i_num) DO NOTHING;
INSERT INTO quest_menu (i_num, str_menu) VALUES (45037, '½ºÆä¼È ½ºÀ§Äª ÇÁ¸®¹Ì¾ö') ON CONFLICT (i_num) DO NOTHING;
INSERT INTO quest_menu (i_num, str_menu) VALUES (45038, 'Exchange [Ultima''s Rune]') ON CONFLICT (i_num) DO NOTHING;
INSERT INTO quest_menu (i_num, str_menu) VALUES (45039, 'Exchange [Ultima''s Rune] x 100') ON CONFLICT (i_num) DO NOTHING;
INSERT INTO quest_menu (i_num, str_menu) VALUES (45040, 'Exchange [Ultima''s Rune] x 420') ON CONFLICT (i_num) DO NOTHING;
INSERT INTO quest_menu (i_num, str_menu) VALUES (45041, 'Exchange [Ultima''s Rune] x 950') ON CONFLICT (i_num) DO NOTHING;
INSERT INTO quest_menu (i_num, str_menu) VALUES (45042, 'Exchange [Spirit Gift Box]') ON CONFLICT (i_num) DO NOTHING;
INSERT INTO quest_menu (i_num, str_menu) VALUES (45043, '[Go to YouTube Channel]') ON CONFLICT (i_num) DO NOTHING;
INSERT INTO quest_menu (i_num, str_menu) VALUES (45044, 'Become a Subscriber') ON CONFLICT (i_num) DO NOTHING;
INSERT INTO quest_menu (i_num, str_menu) VALUES (45045, 'Facebook Event') ON CONFLICT (i_num) DO NOTHING;
INSERT INTO quest_menu (i_num, str_menu) VALUES (45046, 'YouTube Event') ON CONFLICT (i_num) DO NOTHING;
INSERT INTO quest_menu (i_num, str_menu) VALUES (45047, 'Exchange [Merchant Association Fund]') ON CONFLICT (i_num) DO NOTHING;
INSERT INTO quest_menu (i_num, str_menu) VALUES (45048, 'Mithril Check') ON CONFLICT (i_num) DO NOTHING;
INSERT INTO quest_menu (i_num, str_menu) VALUES (45049, 'Platinum Check') ON CONFLICT (i_num) DO NOTHING;
INSERT INTO quest_menu (i_num, str_menu) VALUES (45050, 'Gold Check') ON CONFLICT (i_num) DO NOTHING;
INSERT INTO quest_menu (i_num, str_menu) VALUES (45051, 'Open YouTube!') ON CONFLICT (i_num) DO NOTHING;
INSERT INTO quest_menu (i_num, str_menu) VALUES (45052, 'Exchange [Mysterious Video Emblem]') ON CONFLICT (i_num) DO NOTHING;
INSERT INTO quest_menu (i_num, str_menu) VALUES (45053, 'White Snow Knight') ON CONFLICT (i_num) DO NOTHING;
INSERT INTO quest_menu (i_num, str_menu) VALUES (45054, '7 - Event Emblem (3 Days)') ON CONFLICT (i_num) DO NOTHING;
INSERT INTO quest_menu (i_num, str_menu) VALUES (45055, '150 - Magic Hammer (10)') ON CONFLICT (i_num) DO NOTHING;
INSERT INTO quest_menu (i_num, str_menu) VALUES (45056, 'Mithril Check - Non-tradable') ON CONFLICT (i_num) DO NOTHING;
INSERT INTO quest_menu (i_num, str_menu) VALUES (45057, 'Platinum Check - Non-tradable') ON CONFLICT (i_num) DO NOTHING;
INSERT INTO quest_menu (i_num, str_menu) VALUES (45058, 'Gold Check - Non-tradable') ON CONFLICT (i_num) DO NOTHING;
INSERT INTO quest_menu (i_num, str_menu) VALUES (45059, 'Mithril Check - Tradable') ON CONFLICT (i_num) DO NOTHING;
INSERT INTO quest_menu (i_num, str_menu) VALUES (45060, 'Platinum Check - Tradable') ON CONFLICT (i_num) DO NOTHING;
INSERT INTO quest_menu (i_num, str_menu) VALUES (45061, 'Gold check - Tradable') ON CONFLICT (i_num) DO NOTHING;
INSERT INTO quest_menu (i_num, str_menu) VALUES (45062, 'Purchase Check') ON CONFLICT (i_num) DO NOTHING;
INSERT INTO quest_menu (i_num, str_menu) VALUES (45063, 'Exchange Check') ON CONFLICT (i_num) DO NOTHING;
INSERT INTO quest_menu (i_num, str_menu) VALUES (45064, 'Mithril Check') ON CONFLICT (i_num) DO NOTHING;
INSERT INTO quest_menu (i_num, str_menu) VALUES (45065, 'Platinum Check') ON CONFLICT (i_num) DO NOTHING;
INSERT INTO quest_menu (i_num, str_menu) VALUES (45066, 'Gold Check') ON CONFLICT (i_num) DO NOTHING;
INSERT INTO quest_menu (i_num, str_menu) VALUES (45067, '¼³³¯ºÎÅÍ ÀÜ¼Ò¸® À¯·É') ON CONFLICT (i_num) DO NOTHING;
INSERT INTO quest_menu (i_num, str_menu) VALUES (45068, 'ÀÌ½½¶õÆ® »ç³É') ON CONFLICT (i_num) DO NOTHING;
INSERT INTO quest_menu (i_num, str_menu) VALUES (45069, '½Å±Ô ·¹µåµå·¡°ï »ç³É') ON CONFLICT (i_num) DO NOTHING;
INSERT INTO quest_menu (i_num, str_menu) VALUES (45070, '±İÅ×µÎ¸¥ º¹ÁÖ¸Ó´Ï') ON CONFLICT (i_num) DO NOTHING;
INSERT INTO quest_menu (i_num, str_menu) VALUES (45071, 'Á¤¿¹ º¸¹°»óÀÚ ±³È¯') ON CONFLICT (i_num) DO NOTHING;
INSERT INTO quest_menu (i_num, str_menu) VALUES (45072, 'Á¤¿¹ º¸¹°»óÀÚ 1°³ ±³È¯') ON CONFLICT (i_num) DO NOTHING;
INSERT INTO quest_menu (i_num, str_menu) VALUES (45073, 'Á¤¿¹ º¸¹°»óÀÚ 11°³±³È¯') ON CONFLICT (i_num) DO NOTHING;
INSERT INTO quest_menu (i_num, str_menu) VALUES (45074, '»óÀÚ ±³È¯') ON CONFLICT (i_num) DO NOTHING;
INSERT INTO quest_menu (i_num, str_menu) VALUES (45075, '¼³³¯¿£ Ãàº¹À»') ON CONFLICT (i_num) DO NOTHING;
INSERT INTO quest_menu (i_num, str_menu) VALUES (45076, '[The Anniversary Emblem]') ON CONFLICT (i_num) DO NOTHING;
INSERT INTO quest_menu (i_num, str_menu) VALUES (45077, '[The Anniversary Emblem] (1 Day)') ON CONFLICT (i_num) DO NOTHING;
INSERT INTO quest_menu (i_num, str_menu) VALUES (45078, '[The Anniversary Emblem] (3 Days)') ON CONFLICT (i_num) DO NOTHING;
INSERT INTO quest_menu (i_num, str_menu) VALUES (45079, '[The Anniversary Emblem] (7 Days)') ON CONFLICT (i_num) DO NOTHING;
INSERT INTO quest_menu (i_num, str_menu) VALUES (45080, '[The Anniversary Emblem] (15 Days)') ON CONFLICT (i_num) DO NOTHING;
INSERT INTO quest_menu (i_num, str_menu) VALUES (45081, '[The Anniversary Emblem] (30 Days)') ON CONFLICT (i_num) DO NOTHING;
INSERT INTO quest_menu (i_num, str_menu) VALUES (45082, '[The Anniversary Emblem Replica]') ON CONFLICT (i_num) DO NOTHING;
INSERT INTO quest_menu (i_num, str_menu) VALUES (45083, 'Magic Attack Scroll') ON CONFLICT (i_num) DO NOTHING;
INSERT INTO quest_menu (i_num, str_menu) VALUES (45084, 'ÀÌ½½¶õÆ® »ç³É ¿Ï·á') ON CONFLICT (i_num) DO NOTHING;
INSERT INTO quest_menu (i_num, str_menu) VALUES (45085, 'Èñ±ÍÇÑ ´ÙÅ©µå·¡°ï ´øÀü ÀÌµ¿') ON CONFLICT (i_num) DO NOTHING;
INSERT INTO quest_menu (i_num, str_menu) VALUES (45086, 'Èñ±ÍÇÑ ´ÙÅ©µå·¡°ï ´øÀü ¼³¸í') ON CONFLICT (i_num) DO NOTHING;
INSERT INTO quest_menu (i_num, str_menu) VALUES (45087, 'Ãàº¹ º¸¹°»óÀÚ') ON CONFLICT (i_num) DO NOTHING;
INSERT INTO quest_menu (i_num, str_menu) VALUES (45088, '°æÃà º¸¹°»óÀÚ') ON CONFLICT (i_num) DO NOTHING;
INSERT INTO quest_menu (i_num, str_menu) VALUES (45089, 'Stellar Tattoo (7 Days)') ON CONFLICT (i_num) DO NOTHING;
INSERT INTO quest_menu (i_num, str_menu) VALUES (45090, 'War Hero Wings (30 Days) - 90 M Noah') ON CONFLICT (i_num) DO NOTHING;
INSERT INTO quest_menu (i_num, str_menu) VALUES (45091, 'Lunar Tattoo (30 Days) - 120 M Noah') ON CONFLICT (i_num) DO NOTHING;
INSERT INTO quest_menu (i_num, str_menu) VALUES (45092, 'Gemstone of Tears') ON CONFLICT (i_num) DO NOTHING;
INSERT INTO quest_menu (i_num, str_menu) VALUES (45093, 'War Hero Wings (30 Days) & Lunar Tattoo (30 Days)') ON CONFLICT (i_num) DO NOTHING;
INSERT INTO quest_menu (i_num, str_menu) VALUES (45094, 'War Hero Wings (30 Days) & Lunar Tattoo (30 Days) - 190 M Noah') ON CONFLICT (i_num) DO NOTHING;
INSERT INTO quest_menu (i_num, str_menu) VALUES (45095, '[Event Emblem] (1day)') ON CONFLICT (i_num) DO NOTHING;
INSERT INTO quest_menu (i_num, str_menu) VALUES (45096, '[100% Resurrection Scroll] - 290 M Noah') ON CONFLICT (i_num) DO NOTHING;
INSERT INTO quest_menu (i_num, str_menu) VALUES (45097, 'Sudden Event') ON CONFLICT (i_num) DO NOTHING;
INSERT INTO quest_menu (i_num, str_menu) VALUES (45098, 'Drake''s Blessing') ON CONFLICT (i_num) DO NOTHING;
INSERT INTO quest_menu (i_num, str_menu) VALUES (45099, '50 - 1,500,000 Noah') ON CONFLICT (i_num) DO NOTHING;
INSERT INTO quest_menu (i_num, str_menu) VALUES (45100, '100 - 3,000,000 Noah') ON CONFLICT (i_num) DO NOTHING;
INSERT INTO quest_menu (i_num, str_menu) VALUES (45101, '300 - 9,000,000 Noah') ON CONFLICT (i_num) DO NOTHING;
INSERT INTO quest_menu (i_num, str_menu) VALUES (45102, '500 - 15,000,000 Noah') ON CONFLICT (i_num) DO NOTHING;
INSERT INTO quest_menu (i_num, str_menu) VALUES (45103, 'Nereids (1 Day)') ON CONFLICT (i_num) DO NOTHING;
INSERT INTO quest_menu (i_num, str_menu) VALUES (45104, '[Event] Battlefield Heroes wings of exchange (30 days)') ON CONFLICT (i_num) DO NOTHING;
INSERT INTO quest_menu (i_num, str_menu) VALUES (45105, 'Hellfire Dragon Wings (7 Days)') ON CONFLICT (i_num) DO NOTHING;
INSERT INTO quest_menu (i_num, str_menu) VALUES (45106, 'Oreads (7 Days)') ON CONFLICT (i_num) DO NOTHING;
INSERT INTO quest_menu (i_num, str_menu) VALUES (45107, 'Magic Bag (7 Days)') ON CONFLICT (i_num) DO NOTHING;
INSERT INTO quest_menu (i_num, str_menu) VALUES (45108, 'Event Emlbem (7 Days)') ON CONFLICT (i_num) DO NOTHING;
INSERT INTO quest_menu (i_num, str_menu) VALUES (45109, 'Pathos Glove (7 Days)') ON CONFLICT (i_num) DO NOTHING;
INSERT INTO quest_menu (i_num, str_menu) VALUES (45110, 'Lunar Tattoo (7 Days)') ON CONFLICT (i_num) DO NOTHING;
INSERT INTO quest_menu (i_num, str_menu) VALUES (45111, 'Minerva Package (7 Days)') ON CONFLICT (i_num) DO NOTHING;
INSERT INTO quest_menu (i_num, str_menu) VALUES (45112, '7 Days Instant Use Item List') ON CONFLICT (i_num) DO NOTHING;
INSERT INTO quest_menu (i_num, str_menu) VALUES (45113, 'Transparent Armor of Minerva (7 days)') ON CONFLICT (i_num) DO NOTHING;
INSERT INTO quest_menu (i_num, str_menu) VALUES (45114, 'Transparent Helmet of Minerva (7 days)') ON CONFLICT (i_num) DO NOTHING;
INSERT INTO quest_menu (i_num, str_menu) VALUES (45115, 'Switching Premium Replacement (1 days)') ON CONFLICT (i_num) DO NOTHING;
INSERT INTO quest_menu (i_num, str_menu) VALUES (45116, 'Switching Premium Replacement (3 days)') ON CONFLICT (i_num) DO NOTHING;
INSERT INTO quest_menu (i_num, str_menu) VALUES (45117, 'Switching Premium Replacement (7 days)') ON CONFLICT (i_num) DO NOTHING;
INSERT INTO quest_menu (i_num, str_menu) VALUES (45118, 'Switching Premium Replacement (10 days)') ON CONFLICT (i_num) DO NOTHING;
INSERT INTO quest_menu (i_num, str_menu) VALUES (45119, 'Switching Premium Replacement (15 days)') ON CONFLICT (i_num) DO NOTHING;
INSERT INTO quest_menu (i_num, str_menu) VALUES (45120, 'Switching Premium Replacement (30 days)') ON CONFLICT (i_num) DO NOTHING;
INSERT INTO quest_menu (i_num, str_menu) VALUES (45121, 'Blessed Water of Grace(5000ea)') ON CONFLICT (i_num) DO NOTHING;
INSERT INTO quest_menu (i_num, str_menu) VALUES (45122, 'Blessed Potion of Spirit(5000ea)') ON CONFLICT (i_num) DO NOTHING;
INSERT INTO quest_menu (i_num, str_menu) VALUES (45123, 'Blessed Potion') ON CONFLICT (i_num) DO NOTHING;
INSERT INTO quest_menu (i_num, str_menu) VALUES (45124, '10ÁÖ³â ¿¥ºí·³ ±³È¯') ON CONFLICT (i_num) DO NOTHING;
INSERT INTO quest_menu (i_num, str_menu) VALUES (45125, '10ÁÖ³â ¿¥ºí·³ (4½Ã°£)') ON CONFLICT (i_num) DO NOTHING;
INSERT INTO quest_menu (i_num, str_menu) VALUES (45126, '10ÁÖ³â ¿¥ºí·³ (7ÀÏ)') ON CONFLICT (i_num) DO NOTHING;
INSERT INTO quest_menu (i_num, str_menu) VALUES (45127, '°æÇèÄ¡ Ç×¾Æ¸® º¸»ó') ON CONFLICT (i_num) DO NOTHING;
INSERT INTO quest_menu (i_num, str_menu) VALUES (45128, 'Free Drake''s Blessing - 50') ON CONFLICT (i_num) DO NOTHING;
INSERT INTO quest_menu (i_num, str_menu) VALUES (45129, 'Happy 16th Anniversary') ON CONFLICT (i_num) DO NOTHING;
INSERT INTO quest_menu (i_num, str_menu) VALUES (45130, 'Dungeon of Ultima & Exchange') ON CONFLICT (i_num) DO NOTHING;
INSERT INTO quest_menu (i_num, str_menu) VALUES (45131, 'Enter Dungeon of Ultima') ON CONFLICT (i_num) DO NOTHING;
INSERT INTO quest_menu (i_num, str_menu) VALUES (45132, 'Exchange [Ultima Piece]') ON CONFLICT (i_num) DO NOTHING;
INSERT INTO quest_menu (i_num, str_menu) VALUES (45133, 'Exchange [Ultima Scent]') ON CONFLICT (i_num) DO NOTHING;
INSERT INTO quest_menu (i_num, str_menu) VALUES (45134, 'Cancel Dungeon of Ultima') ON CONFLICT (i_num) DO NOTHING;
INSERT INTO quest_menu (i_num, str_menu) VALUES (45135, 'Open Character Recovery') ON CONFLICT (i_num) DO NOTHING;
INSERT INTO quest_menu (i_num, str_menu) VALUES (45136, '[Empires Emblem] (30 days)') ON CONFLICT (i_num) DO NOTHING;
INSERT INTO quest_menu (i_num, str_menu) VALUES (45137, '[Empires Emblem] (30 days)') ON CONFLICT (i_num) DO NOTHING;
INSERT INTO quest_menu (i_num, str_menu) VALUES (45138, '»çÀÚÀÇ Èû ÁÖ¹®¼­(¼Ò) - 5°³') ON CONFLICT (i_num) DO NOTHING;
INSERT INTO quest_menu (i_num, str_menu) VALUES (45139, 'ÅÂ¾çÀÇ Å¸Åõ ±³È¯±Ç(30ÀÏ) - 25°³') ON CONFLICT (i_num) DO NOTHING;
INSERT INTO quest_menu (i_num, str_menu) VALUES (45140, 'È­·æÀÇ ºñ´Ã - 35°³') ON CONFLICT (i_num) DO NOTHING;
INSERT INTO quest_menu (i_num, str_menu) VALUES (45141, 'Æ®¶óÀÌ³ªÀÇ Á¶°¢ - 45°³') ON CONFLICT (i_num) DO NOTHING;
INSERT INTO quest_menu (i_num, str_menu) VALUES (45142, '·Î°í½ºÀÇ °¡È£ - 50°³') ON CONFLICT (i_num) DO NOTHING;
INSERT INTO quest_menu (i_num, str_menu) VALUES (45143, 'Fortune Box Purchase') ON CONFLICT (i_num) DO NOTHING;
INSERT INTO quest_menu (i_num, str_menu) VALUES (45144, '¾ğ´õ ´õ Ä³½½ ¹«±â ±³È¯±Ç - 130°³') ON CONFLICT (i_num) DO NOTHING;
INSERT INTO quest_menu (i_num, str_menu) VALUES (45145, 'Fortune Box Purchase') ON CONFLICT (i_num) DO NOTHING;
INSERT INTO quest_menu (i_num, str_menu) VALUES (45146, 'Fortune Box Purchase') ON CONFLICT (i_num) DO NOTHING;
INSERT INTO quest_menu (i_num, str_menu) VALUES (45147, 'Fortune Box ') ON CONFLICT (i_num) DO NOTHING;
INSERT INTO quest_menu (i_num, str_menu) VALUES (45148, 'Today''s Lucky Chance') ON CONFLICT (i_num) DO NOTHING;
INSERT INTO quest_menu (i_num, str_menu) VALUES (45149, 'Exchange [Magic Attack Scroll*10]') ON CONFLICT (i_num) DO NOTHING;
INSERT INTO quest_menu (i_num, str_menu) VALUES (45150, '250 - Old Draki Supply Box') ON CONFLICT (i_num) DO NOTHING;
INSERT INTO quest_menu (i_num, str_menu) VALUES (45151, '350 - Draki Supply Box') ON CONFLICT (i_num) DO NOTHING;
INSERT INTO quest_menu (i_num, str_menu) VALUES (45152, '200 - Draki Supply Box') ON CONFLICT (i_num) DO NOTHING;
INSERT INTO quest_menu (i_num, str_menu) VALUES (45153, '200 - Draki Supply Box') ON CONFLICT (i_num) DO NOTHING;
INSERT INTO quest_menu (i_num, str_menu) VALUES (45154, '[Limited] Gryphon') ON CONFLICT (i_num) DO NOTHING;
INSERT INTO quest_menu (i_num, str_menu) VALUES (45155, '[Limited] Valkyrie') ON CONFLICT (i_num) DO NOTHING;
INSERT INTO quest_menu (i_num, str_menu) VALUES (45156, '[Limited] Bahamut') ON CONFLICT (i_num) DO NOTHING;
INSERT INTO quest_menu (i_num, str_menu) VALUES (45157, '[Limited] Minerva Exchange') ON CONFLICT (i_num) DO NOTHING;
INSERT INTO quest_menu (i_num, str_menu) VALUES (45158, 'Helmet') ON CONFLICT (i_num) DO NOTHING;
INSERT INTO quest_menu (i_num, str_menu) VALUES (45159, 'Armor') ON CONFLICT (i_num) DO NOTHING;
INSERT INTO quest_menu (i_num, str_menu) VALUES (45160, 'HP +220 + 2% increase') ON CONFLICT (i_num) DO NOTHING;
INSERT INTO quest_menu (i_num, str_menu) VALUES (45161, 'Defense Power +33 + 2% increase') ON CONFLICT (i_num) DO NOTHING;
INSERT INTO quest_menu (i_num, str_menu) VALUES (45162, '[Akara Altar] How to Use') ON CONFLICT (i_num) DO NOTHING;
INSERT INTO quest_menu (i_num, str_menu) VALUES (45163, '[Akara Altar] Basic Info') ON CONFLICT (i_num) DO NOTHING;
INSERT INTO quest_menu (i_num, str_menu) VALUES (45164, 'Bidding and Claim') ON CONFLICT (i_num) DO NOTHING;
INSERT INTO quest_menu (i_num, str_menu) VALUES (45165, '[Akara Altar] Time') ON CONFLICT (i_num) DO NOTHING;
INSERT INTO quest_menu (i_num, str_menu) VALUES (45166, '[Limited] Minerva Purchase & Exchange') ON CONFLICT (i_num) DO NOTHING;
INSERT INTO quest_menu (i_num, str_menu) VALUES (45167, '[Limited] Minerva(30 days) Purchase') ON CONFLICT (i_num) DO NOTHING;
INSERT INTO quest_menu (i_num, str_menu) VALUES (45168, 'HP +110 + 1% increase') ON CONFLICT (i_num) DO NOTHING;
INSERT INTO quest_menu (i_num, str_menu) VALUES (45169, 'Defense Power +22 + 1% increase') ON CONFLICT (i_num) DO NOTHING;
INSERT INTO quest_menu (i_num, str_menu) VALUES (45170, 'Fortified Fishing Rod') ON CONFLICT (i_num) DO NOTHING;
INSERT INTO quest_menu (i_num, str_menu) VALUES (45171, 'Copper Fishing Rod') ON CONFLICT (i_num) DO NOTHING;
INSERT INTO quest_menu (i_num, str_menu) VALUES (45172, 'Bronze Fishing Rod') ON CONFLICT (i_num) DO NOTHING;
INSERT INTO quest_menu (i_num, str_menu) VALUES (45173, 'Iron Fishing Rod') ON CONFLICT (i_num) DO NOTHING;
INSERT INTO quest_menu (i_num, str_menu) VALUES (45174, 'Steel Fishing Rod') ON CONFLICT (i_num) DO NOTHING;
INSERT INTO quest_menu (i_num, str_menu) VALUES (45175, 'Mithrill Fishing Rod') ON CONFLICT (i_num) DO NOTHING;
INSERT INTO quest_menu (i_num, str_menu) VALUES (45176, 'Fish for Sale') ON CONFLICT (i_num) DO NOTHING;
INSERT INTO quest_menu (i_num, str_menu) VALUES (45177, 'Fortify Fishing Rod') ON CONFLICT (i_num) DO NOTHING;
INSERT INTO quest_menu (i_num, str_menu) VALUES (45178, 'HP +220 + 2% increase') ON CONFLICT (i_num) DO NOTHING;
INSERT INTO quest_menu (i_num, str_menu) VALUES (45179, 'Defense Power +33 + 2% increase') ON CONFLICT (i_num) DO NOTHING;
INSERT INTO quest_menu (i_num, str_menu) VALUES (45180, '4% damage increase to Warrior Class') ON CONFLICT (i_num) DO NOTHING;
INSERT INTO quest_menu (i_num, str_menu) VALUES (45181, '4% damage increase to Rogue Class') ON CONFLICT (i_num) DO NOTHING;
INSERT INTO quest_menu (i_num, str_menu) VALUES (45182, '4% damage increase to Magician Class') ON CONFLICT (i_num) DO NOTHING;
INSERT INTO quest_menu (i_num, str_menu) VALUES (45183, '4% damage increase to Priest Class') ON CONFLICT (i_num) DO NOTHING;
INSERT INTO quest_menu (i_num, str_menu) VALUES (45184, '4% defense increase against Warrior Class') ON CONFLICT (i_num) DO NOTHING;
INSERT INTO quest_menu (i_num, str_menu) VALUES (45185, '4% defense increase against Rogue Class') ON CONFLICT (i_num) DO NOTHING;
INSERT INTO quest_menu (i_num, str_menu) VALUES (45186, '4% defense increase against Magician Class') ON CONFLICT (i_num) DO NOTHING;
INSERT INTO quest_menu (i_num, str_menu) VALUES (45187, '4% defense increase against Priest Class') ON CONFLICT (i_num) DO NOTHING;
INSERT INTO quest_menu (i_num, str_menu) VALUES (45188, '[Limited]Pathos'' Glove') ON CONFLICT (i_num) DO NOTHING;
INSERT INTO quest_menu (i_num, str_menu) VALUES (45189, 'Scroll of 2200HP Up & Armor 380') ON CONFLICT (i_num) DO NOTHING;
INSERT INTO quest_menu (i_num, str_menu) VALUES (45190, 'Scroll of Atk 22%Up & 2200HP Up & Armor 380') ON CONFLICT (i_num) DO NOTHING;
INSERT INTO quest_menu (i_num, str_menu) VALUES (45191, 'Limited Edition Buff Scroll') ON CONFLICT (i_num) DO NOTHING;
INSERT INTO quest_menu (i_num, str_menu) VALUES (45192, 'Purchase Ibexs/Crisis Potion') ON CONFLICT (i_num) DO NOTHING;
INSERT INTO quest_menu (i_num, str_menu) VALUES (45193, 'Purchase Ibexs Potion') ON CONFLICT (i_num) DO NOTHING;
INSERT INTO quest_menu (i_num, str_menu) VALUES (45194, 'Purchase Crisis Potion') ON CONFLICT (i_num) DO NOTHING;
INSERT INTO quest_menu (i_num, str_menu) VALUES (45195, 'Purchase Resurrection Scroll 90%') ON CONFLICT (i_num) DO NOTHING;
INSERT INTO quest_menu (i_num, str_menu) VALUES (45196, '50 - 3,000,000 Noah') ON CONFLICT (i_num) DO NOTHING;
INSERT INTO quest_menu (i_num, str_menu) VALUES (45197, '100 - 6,000,000 Noah') ON CONFLICT (i_num) DO NOTHING;
INSERT INTO quest_menu (i_num, str_menu) VALUES (45198, '300 - 18,000,000 Noah') ON CONFLICT (i_num) DO NOTHING;
INSERT INTO quest_menu (i_num, str_menu) VALUES (45199, '500 - 30,000,000 Noah') ON CONFLICT (i_num) DO NOTHING;
INSERT INTO quest_menu (i_num, str_menu) VALUES (45200, '±¹¿Õ³¯°³ - °ø°İ·Â') ON CONFLICT (i_num) DO NOTHING;
INSERT INTO quest_menu (i_num, str_menu) VALUES (45201, '±¹¿Õ³¯°³ - ¹æ¾î·Â') ON CONFLICT (i_num) DO NOTHING;
INSERT INTO quest_menu (i_num, str_menu) VALUES (45202, '[Akara Altar]') ON CONFLICT (i_num) DO NOTHING;
INSERT INTO quest_menu (i_num, str_menu) VALUES (45203, 'Checking Cumulative Warnings') ON CONFLICT (i_num) DO NOTHING;
INSERT INTO quest_menu (i_num, str_menu) VALUES (45204, 'Resetting Cumulative Warnings') ON CONFLICT (i_num) DO NOTHING;
INSERT INTO quest_menu (i_num, str_menu) VALUES (45205, '[ÀÌº¥Æ®]¹Ì½º¸± Á¶°¢ ±³È¯') ON CONFLICT (i_num) DO NOTHING;
INSERT INTO quest_menu (i_num, str_menu) VALUES (45206, 'È¦¸®³ªÀÌÆ®&´ÙÅ©³ªÀÌÆ®¹«±â ±³È¯') ON CONFLICT (i_num) DO NOTHING;
INSERT INTO quest_menu (i_num, str_menu) VALUES (45207, 'È­·æÀÇ ±êÅĞ ÀüºÎ Àû¸³') ON CONFLICT (i_num) DO NOTHING;
INSERT INTO quest_menu (i_num, str_menu) VALUES (45208, 'È­·æÀÇ ±êÅĞ 10°³ Àû¸³') ON CONFLICT (i_num) DO NOTHING;
INSERT INTO quest_menu (i_num, str_menu) VALUES (45209, 'User Buff Pet Scroll - HP 200') ON CONFLICT (i_num) DO NOTHING;
INSERT INTO quest_menu (i_num, str_menu) VALUES (45210, 'User Buff Pet Scroll - AC 20') ON CONFLICT (i_num) DO NOTHING;
INSERT INTO quest_menu (i_num, str_menu) VALUES (45211, 'User Buff Pet Scroll - Atk 5') ON CONFLICT (i_num) DO NOTHING;
INSERT INTO quest_menu (i_num, str_menu) VALUES (45212, 'User Buff Pet Scroll - HP 200(1 day)') ON CONFLICT (i_num) DO NOTHING;
INSERT INTO quest_menu (i_num, str_menu) VALUES (45213, 'User Buff Pet Scroll - HP 200(3 day)') ON CONFLICT (i_num) DO NOTHING;
INSERT INTO quest_menu (i_num, str_menu) VALUES (45214, 'User Buff Pet Scroll - HP 200(7 day)') ON CONFLICT (i_num) DO NOTHING;
INSERT INTO quest_menu (i_num, str_menu) VALUES (45215, 'User Buff Pet Scroll - HP 200(15 day)') ON CONFLICT (i_num) DO NOTHING;
INSERT INTO quest_menu (i_num, str_menu) VALUES (45216, 'User Buff Pet Scroll - HP 200(30 day)') ON CONFLICT (i_num) DO NOTHING;
INSERT INTO quest_menu (i_num, str_menu) VALUES (45217, 'User Buff Pet Scroll - AC 20(1 day)') ON CONFLICT (i_num) DO NOTHING;
INSERT INTO quest_menu (i_num, str_menu) VALUES (45218, 'User Buff Pet Scroll - AC 20(3 day)') ON CONFLICT (i_num) DO NOTHING;
INSERT INTO quest_menu (i_num, str_menu) VALUES (45219, 'User Buff Pet Scroll - AC 20(7 day)') ON CONFLICT (i_num) DO NOTHING;
INSERT INTO quest_menu (i_num, str_menu) VALUES (45220, 'User Buff Pet Scroll - AC 20(15 day)') ON CONFLICT (i_num) DO NOTHING;
INSERT INTO quest_menu (i_num, str_menu) VALUES (45221, 'User Buff Pet Scroll - AC 20(30 day)') ON CONFLICT (i_num) DO NOTHING;
INSERT INTO quest_menu (i_num, str_menu) VALUES (45222, 'User Buff Pet Scroll - Atk 5(1 day)') ON CONFLICT (i_num) DO NOTHING;
INSERT INTO quest_menu (i_num, str_menu) VALUES (45223, 'User Buff Pet Scroll - Atk 5(3 day)') ON CONFLICT (i_num) DO NOTHING;
INSERT INTO quest_menu (i_num, str_menu) VALUES (45224, 'User Buff Pet Scroll - Atk 5(7 day)') ON CONFLICT (i_num) DO NOTHING;
INSERT INTO quest_menu (i_num, str_menu) VALUES (45225, 'User Buff Pet Scroll - Atk 5(15 day)') ON CONFLICT (i_num) DO NOTHING;
INSERT INTO quest_menu (i_num, str_menu) VALUES (45226, 'User Buff Pet Scroll - Atk 5(30 day)') ON CONFLICT (i_num) DO NOTHING;
INSERT INTO quest_menu (i_num, str_menu) VALUES (45227, 'User Buff Pet Scroll') ON CONFLICT (i_num) DO NOTHING;
INSERT INTO quest_menu (i_num, str_menu) VALUES (45228, 'Progress of Attendance Check') ON CONFLICT (i_num) DO NOTHING;
INSERT INTO quest_menu (i_num, str_menu) VALUES (45229, 'Exchange of Attendance Check Voucher') ON CONFLICT (i_num) DO NOTHING;
INSERT INTO quest_menu (i_num, str_menu) VALUES (45230, '1 - Can exchange with only 1 out of 4 types of Gems. ') ON CONFLICT (i_num) DO NOTHING;
INSERT INTO quest_menu (i_num, str_menu) VALUES (45231, '3 - Armor & Weapon Enchant Scroll') ON CONFLICT (i_num) DO NOTHING;
INSERT INTO quest_menu (i_num, str_menu) VALUES (45232, '5 - Alencia Wing (3Days)') ON CONFLICT (i_num) DO NOTHING;
INSERT INTO quest_menu (i_num, str_menu) VALUES (45233, '7 - VIP Vault Key (7 Days)') ON CONFLICT (i_num) DO NOTHING;
INSERT INTO quest_menu (i_num, str_menu) VALUES (45234, '10 - Magic hammer') ON CONFLICT (i_num) DO NOTHING;
INSERT INTO quest_menu (i_num, str_menu) VALUES (45235, '14 - Lunar Tattoo (15 Days)') ON CONFLICT (i_num) DO NOTHING;
INSERT INTO quest_menu (i_num, str_menu) VALUES (45236, 'I Love Knight online') ON CONFLICT (i_num) DO NOTHING;
INSERT INTO quest_menu (i_num, str_menu) VALUES (45237, 'User Buff Pet Scroll - HP 200 - 50M') ON CONFLICT (i_num) DO NOTHING;
INSERT INTO quest_menu (i_num, str_menu) VALUES (45238, 'User Buff Pet Scroll - AC 20 - 50M') ON CONFLICT (i_num) DO NOTHING;
INSERT INTO quest_menu (i_num, str_menu) VALUES (45239, 'User Buff Pet Scroll - Atk 5 - 60M') ON CONFLICT (i_num) DO NOTHING;
INSERT INTO quest_menu (i_num, str_menu) VALUES (45240, '[Akara Altar]') ON CONFLICT (i_num) DO NOTHING;
INSERT INTO quest_menu (i_num, str_menu) VALUES (45241, 'Special Defense Scroll') ON CONFLICT (i_num) DO NOTHING;
INSERT INTO quest_menu (i_num, str_menu) VALUES (45242, 'Dagger Defense Scroll') ON CONFLICT (i_num) DO NOTHING;
INSERT INTO quest_menu (i_num, str_menu) VALUES (45243, 'Jamadar Defense Scroll') ON CONFLICT (i_num) DO NOTHING;
INSERT INTO quest_menu (i_num, str_menu) VALUES (45244, 'Sword Defense Scroll') ON CONFLICT (i_num) DO NOTHING;
INSERT INTO quest_menu (i_num, str_menu) VALUES (45245, 'Mace Defense Scroll') ON CONFLICT (i_num) DO NOTHING;
INSERT INTO quest_menu (i_num, str_menu) VALUES (45246, 'Axe Defense Scroll') ON CONFLICT (i_num) DO NOTHING;
INSERT INTO quest_menu (i_num, str_menu) VALUES (45247, 'Spear Defense Scroll') ON CONFLICT (i_num) DO NOTHING;
INSERT INTO quest_menu (i_num, str_menu) VALUES (45248, 'Bow/Crossbow Defense Scroll') ON CONFLICT (i_num) DO NOTHING;
INSERT INTO quest_menu (i_num, str_menu) VALUES (45249, '[µå·¡°ï »óÀÚ]¹°¾à ±³È¯±Ç') ON CONFLICT (i_num) DO NOTHING;
INSERT INTO quest_menu (i_num, str_menu) VALUES (45250, '[µå·¡°ï »óÀÚ]¾ÆÀÌº¤½º ¹°¾à ±³È¯') ON CONFLICT (i_num) DO NOTHING;
INSERT INTO quest_menu (i_num, str_menu) VALUES (45251, '[µå·¡°ï »óÀÚ]Å©¶óÀÌ½Ã½º ¹°¾à ±³È¯') ON CONFLICT (i_num) DO NOTHING;
INSERT INTO quest_menu (i_num, str_menu) VALUES (45252, '¶óÅ×ÀÌ³ë ºÎ¸§ Áö±Ş ¾ÆÀÌÅÛ »èÁ¦') ON CONFLICT (i_num) DO NOTHING;
INSERT INTO quest_menu (i_num, str_menu) VALUES (45253, '¹«»ó ¹öÇÁ ÀÌ¿ë±Ç') ON CONFLICT (i_num) DO NOTHING;
INSERT INTO quest_menu (i_num, str_menu) VALUES (45254, '¹«»ó ¾ÆÀÌÅÛ ÀÌ¿ë±Ç') ON CONFLICT (i_num) DO NOTHING;
INSERT INTO quest_menu (i_num, str_menu) VALUES (45255, 'º¹±ÍÀÚ ÀÌº¥Æ®') ON CONFLICT (i_num) DO NOTHING;
INSERT INTO quest_menu (i_num, str_menu) VALUES (45256, 'Alencia Wing (blue) exchange (1 days)') ON CONFLICT (i_num) DO NOTHING;
INSERT INTO quest_menu (i_num, str_menu) VALUES (45257, '·Î°í½ºÀÇ ºÎ¸§') ON CONFLICT (i_num) DO NOTHING;
INSERT INTO quest_menu (i_num, str_menu) VALUES (45258, '2022 Snow Crystals') ON CONFLICT (i_num) DO NOTHING;
INSERT INTO quest_menu (i_num, str_menu) VALUES (45259, 'Certificate of Pathos'' Glove') ON CONFLICT (i_num) DO NOTHING;
INSERT INTO quest_menu (i_num, str_menu) VALUES (45260, 'Noah Pathos''s Gloves Certificate') ON CONFLICT (i_num) DO NOTHING;
INSERT INTO quest_menu (i_num, str_menu) VALUES (45261, 'ÆÄÅä½ºÀÇ Àå°©') ON CONFLICT (i_num) DO NOTHING;
INSERT INTO quest_menu (i_num, str_menu) VALUES (45262, '¹Ì³×¸£¹Ù ÀÇ Àå°©') ON CONFLICT (i_num) DO NOTHING;
INSERT INTO quest_menu (i_num, str_menu) VALUES (45263, 'Contest Confirmation') ON CONFLICT (i_num) DO NOTHING;
INSERT INTO quest_menu (i_num, str_menu) VALUES (45264, 'Fishing Notebook Writing Contest') ON CONFLICT (i_num) DO NOTHING;
INSERT INTO quest_menu (i_num, str_menu) VALUES (45265, 'Guerrilla Contest') ON CONFLICT (i_num) DO NOTHING;
INSERT INTO quest_menu (i_num, str_menu) VALUES (45266, 'Cumulative Period Fish Fishing Contest') ON CONFLICT (i_num) DO NOTHING;
INSERT INTO quest_menu (i_num, str_menu) VALUES (45267, 'Many Award - Number of Fish') ON CONFLICT (i_num) DO NOTHING;
INSERT INTO quest_menu (i_num, str_menu) VALUES (45268, 'Big Award - Length') ON CONFLICT (i_num) DO NOTHING;
INSERT INTO quest_menu (i_num, str_menu) VALUES (45269, 'Sales Award - Sales') ON CONFLICT (i_num) DO NOTHING;
INSERT INTO quest_menu (i_num, str_menu) VALUES (45270, 'View Competition Status') ON CONFLICT (i_num) DO NOTHING;
INSERT INTO quest_menu (i_num, str_menu) VALUES (45271, 'Return the Fish') ON CONFLICT (i_num) DO NOTHING;
INSERT INTO quest_menu (i_num, str_menu) VALUES (45272, 'Lets start fishing') ON CONFLICT (i_num) DO NOTHING;
INSERT INTO quest_menu (i_num, str_menu) VALUES (45273, 'Record Competition (for past competitions)') ON CONFLICT (i_num) DO NOTHING;
INSERT INTO quest_menu (i_num, str_menu) VALUES (45274, 'Record Competition (for past competitions) - Count') ON CONFLICT (i_num) DO NOTHING;
INSERT INTO quest_menu (i_num, str_menu) VALUES (45275, 'Record Competition (for past competitions) - Length') ON CONFLICT (i_num) DO NOTHING;
INSERT INTO quest_menu (i_num, str_menu) VALUES (45276, 'Record Competition (for past competitions) - Sales') ON CONFLICT (i_num) DO NOTHING;
INSERT INTO quest_menu (i_num, str_menu) VALUES (45277, 'Retired Angler''s request') ON CONFLICT (i_num) DO NOTHING;
INSERT INTO quest_menu (i_num, str_menu) VALUES (45278, 'How to Fish') ON CONFLICT (i_num) DO NOTHING;
INSERT INTO quest_menu (i_num, str_menu) VALUES (45279, 'Exchange of the Ark of the Saint') ON CONFLICT (i_num) DO NOTHING;
INSERT INTO quest_menu (i_num, str_menu) VALUES (45280, 'View Competition Information') ON CONFLICT (i_num) DO NOTHING;
INSERT INTO quest_menu (i_num, str_menu) VALUES (45281, 'View Daily Quest Information') ON CONFLICT (i_num) DO NOTHING;
INSERT INTO quest_menu (i_num, str_menu) VALUES (45282, 'Quest Complete') ON CONFLICT (i_num) DO NOTHING;
INSERT INTO quest_menu (i_num, str_menu) VALUES (45283, 'Quest Complete') ON CONFLICT (i_num) DO NOTHING;
INSERT INTO quest_menu (i_num, str_menu) VALUES (45284, '100Á¡ - ÀÌµ¿¼ÓµµÁõ°¡¹°¾à(3È¸)') ON CONFLICT (i_num) DO NOTHING;
INSERT INTO quest_menu (i_num, str_menu) VALUES (45285, '300Á¡ - 250 ¹æ¾î·Â Áõ°¡ ÁÖ¹®¼­(3È¸)') ON CONFLICT (i_num) DO NOTHING;
INSERT INTO quest_menu (i_num, str_menu) VALUES (45286, '500Á¡ - 2000HP Áõ°¡ ÁÖ¹®¼­(3È¸)') ON CONFLICT (i_num) DO NOTHING;
INSERT INTO quest_menu (i_num, str_menu) VALUES (45287, '1000Á¡ - º°Æ· Å¸Åõ ±³È¯±Ç(15ÀÏ)') ON CONFLICT (i_num) DO NOTHING;
INSERT INTO quest_menu (i_num, str_menu) VALUES (45288, '1500Á¡ - ½ºÀ§Äª ÇÁ¸®¹Ì¾ö ±³È¯±Ç(1ÀÏ)') ON CONFLICT (i_num) DO NOTHING;
INSERT INTO quest_menu (i_num, str_menu) VALUES (45289, '2000Á¡ - ÀüÀåÀÇ ¿µ¿õÀÇ ³¯°³ ±³È¯±Ç(!5ÀÏ)') ON CONFLICT (i_num) DO NOTHING;
INSERT INTO quest_menu (i_num, str_menu) VALUES (45290, '¸í¿¹ Æ÷ÀÎÆ® ±³È¯') ON CONFLICT (i_num) DO NOTHING;
INSERT INTO quest_menu (i_num, str_menu) VALUES (45291, 'Magpie NPC Transformation Manual Coupon') ON CONFLICT (i_num) DO NOTHING;
INSERT INTO quest_menu (i_num, str_menu) VALUES (45292, '¹«»ó ´ë¿© ¹öÇÁ±Ç ½Ã°£Á¦·Î ±³È¯') ON CONFLICT (i_num) DO NOTHING;
INSERT INTO quest_menu (i_num, str_menu) VALUES (45293, 'EXP Premium Exchange Voucher(7Days)') ON CONFLICT (i_num) DO NOTHING;
INSERT INTO quest_menu (i_num, str_menu) VALUES (45294, 'Switching Premium Exchange Voucher(30Days)') ON CONFLICT (i_num) DO NOTHING;
INSERT INTO quest_menu (i_num, str_menu) VALUES (45295, 'WAR Premium Exchange Voucher(7Days)') ON CONFLICT (i_num) DO NOTHING;
INSERT INTO quest_menu (i_num, str_menu) VALUES (45296, 'Premium Exchange Voucher') ON CONFLICT (i_num) DO NOTHING;
INSERT INTO quest_menu (i_num, str_menu) VALUES (45297, 'Premium Use & Exchange Voucher') ON CONFLICT (i_num) DO NOTHING;
INSERT INTO quest_menu (i_num, str_menu) VALUES (45298, '½ºÀ§Äª ÇÁ¸®¹Ì¾ö °Å·¡ºÒ°¡(30ÀÏ)') ON CONFLICT (i_num) DO NOTHING;
INSERT INTO quest_menu (i_num, str_menu) VALUES (45299, '¾ÆÀÌÅÛ ¸Å´Ï¾Æ ¿¥ºí·³ ±³È¯±Ç') ON CONFLICT (i_num) DO NOTHING;
INSERT INTO quest_menu (i_num, str_menu) VALUES (45300, 'Ã¤³Î¸µ ·¹º§ ´Ş¼º º¸»ó') ON CONFLICT (i_num) DO NOTHING;
INSERT INTO quest_menu (i_num, str_menu) VALUES (45301, 'º¸»ó ¹Ş±â') ON CONFLICT (i_num) DO NOTHING;
INSERT INTO quest_menu (i_num, str_menu) VALUES (45302, 'Chaos Tournament Application') ON CONFLICT (i_num) DO NOTHING;
INSERT INTO quest_menu (i_num, str_menu) VALUES (45303, 'I will apply.') ON CONFLICT (i_num) DO NOTHING;
INSERT INTO quest_menu (i_num, str_menu) VALUES (45304, 'I''ll think about it.') ON CONFLICT (i_num) DO NOTHING;
INSERT INTO quest_menu (i_num, str_menu) VALUES (45305, 'I will cancel it.') ON CONFLICT (i_num) DO NOTHING;
INSERT INTO quest_menu (i_num, str_menu) VALUES (45306, 'Get Costumes and Decorative Emblems') ON CONFLICT (i_num) DO NOTHING;
INSERT INTO quest_menu (i_num, str_menu) VALUES (45307, 'Remove Indestructible Items') ON CONFLICT (i_num) DO NOTHING;
INSERT INTO quest_menu (i_num, str_menu) VALUES (45308, '°ñµå µå·¡°ï »óÀÚ') ON CONFLICT (i_num) DO NOTHING;
INSERT INTO quest_menu (i_num, str_menu) VALUES (45309, ' Defeat 200 enemies') ON CONFLICT (i_num) DO NOTHING;
INSERT INTO quest_menu (i_num, str_menu) VALUES (45310, 'ÇÁ¸®¹Ì¾ö Ãß°¡º¸»ó ÀÌº¥Æ®') ON CONFLICT (i_num) DO NOTHING;
INSERT INTO quest_menu (i_num, str_menu) VALUES (45311, 'Prayer of Priests [Limited Edition]') ON CONFLICT (i_num) DO NOTHING;
INSERT INTO quest_menu (i_num, str_menu) VALUES (45312, '°ñµå µå·¡°ï »óÀÚX5') ON CONFLICT (i_num) DO NOTHING;
INSERT INTO quest_menu (i_num, str_menu) VALUES (45313, 'Çà¿îÀÇ ³×ÀÙÅ¬·Î¹ö') ON CONFLICT (i_num) DO NOTHING;
INSERT INTO quest_menu (i_num, str_menu) VALUES (45314, 'I Love Knight online2') ON CONFLICT (i_num) DO NOTHING;
INSERT INTO quest_menu (i_num, str_menu) VALUES (45315, 'Appreciation of Logos') ON CONFLICT (i_num) DO NOTHING;
INSERT INTO quest_menu (i_num, str_menu) VALUES (45316, 'Call of Logos') ON CONFLICT (i_num) DO NOTHING;
INSERT INTO quest_menu (i_num, str_menu) VALUES (45317, '¾ÆÄ«¶óÀÇ ¾Ç¼¼¼­¸® »óÀÚ') ON CONFLICT (i_num) DO NOTHING;
INSERT INTO quest_menu (i_num, str_menu) VALUES (45318, ' Defeat 50 enemies') ON CONFLICT (i_num) DO NOTHING;
INSERT INTO quest_menu (i_num, str_menu) VALUES (45319, 'Re-enter the tournament') ON CONFLICT (i_num) DO NOTHING;
INSERT INTO quest_menu (i_num, str_menu) VALUES (45320, 'Receive 18th Anniversary Gift') ON CONFLICT (i_num) DO NOTHING;
INSERT INTO quest_menu (i_num, str_menu) VALUES (45321, '[Knight Online 18th Anniversary Emblem]') ON CONFLICT (i_num) DO NOTHING;
INSERT INTO quest_menu (i_num, str_menu) VALUES (45322, '[Knight Online 18th Anniversary Emblem] Exchange(1day)') ON CONFLICT (i_num) DO NOTHING;
INSERT INTO quest_menu (i_num, str_menu) VALUES (45323, '[Knight Online 18th Anniversary Emblem] Exchange(3days)') ON CONFLICT (i_num) DO NOTHING;
INSERT INTO quest_menu (i_num, str_menu) VALUES (45324, '[Knight Online 18th Anniversary Emblem] Exchange(7days)') ON CONFLICT (i_num) DO NOTHING;
INSERT INTO quest_menu (i_num, str_menu) VALUES (45325, '[Knight Online 18th Anniversary Emblem] Exchange(15days)') ON CONFLICT (i_num) DO NOTHING;
INSERT INTO quest_menu (i_num, str_menu) VALUES (45326, '[Knight Online 18th Anniversary Emblem] Exchange(30days)') ON CONFLICT (i_num) DO NOTHING;
INSERT INTO quest_menu (i_num, str_menu) VALUES (45327, '[Knight Online 18th Anniversary Decorative Emblem]') ON CONFLICT (i_num) DO NOTHING;
INSERT INTO quest_menu (i_num, str_menu) VALUES (45328, 'Redistribution Scroll-Untradable Exchange') ON CONFLICT (i_num) DO NOTHING;
INSERT INTO quest_menu (i_num, str_menu) VALUES (45329, 'I would like to apply to participate in Forgotten Temple.') ON CONFLICT (i_num) DO NOTHING;
INSERT INTO quest_menu (i_num, str_menu) VALUES (45330, 'Manes'' Orb Exchange') ON CONFLICT (i_num) DO NOTHING;
INSERT INTO quest_menu (i_num, str_menu) VALUES (45331, '15 - Magpie mom transformation order sheet') ON CONFLICT (i_num) DO NOTHING;
INSERT INTO quest_menu (i_num, str_menu) VALUES (45332, '45- Oreads (1 Days)') ON CONFLICT (i_num) DO NOTHING;
INSERT INTO quest_menu (i_num, str_menu) VALUES (45333, '450 - Lunar Tattoo (15 Days)') ON CONFLICT (i_num) DO NOTHING;
INSERT INTO quest_menu (i_num, str_menu) VALUES (45334, 'How to enter Forgotten Temple') ON CONFLICT (i_num) DO NOTHING;
INSERT INTO quest_menu (i_num, str_menu) VALUES (45335, 'How to enter Under the Castle') ON CONFLICT (i_num) DO NOTHING;
INSERT INTO quest_menu (i_num, str_menu) VALUES (45336, 'Draki Title Exchange') ON CONFLICT (i_num) DO NOTHING;
INSERT INTO quest_menu (i_num, str_menu) VALUES (45337, '700 - [The Anniversary Emblem Replica]') ON CONFLICT (i_num) DO NOTHING;
INSERT INTO quest_menu (i_num, str_menu) VALUES (45338, 'º°ÀÇ Å¸Åõ (3ÀÏ) ±³È¯') ON CONFLICT (i_num) DO NOTHING;
INSERT INTO quest_menu (i_num, str_menu) VALUES (45339, 'Captcha Point Deduction') ON CONFLICT (i_num) DO NOTHING;
INSERT INTO quest_menu (i_num, str_menu) VALUES (45340, '·ê·¿ ÇÁ¸®¹Ì¾ö ±³È¯') ON CONFLICT (i_num) DO NOTHING;
INSERT INTO quest_menu (i_num, str_menu) VALUES (45341, '·ê·¿ ÇÁ¸®¹Ì¾ö ±³È¯±Ç ±³È¯') ON CONFLICT (i_num) DO NOTHING;
INSERT INTO quest_menu (i_num, str_menu) VALUES (45342, '·ê·¿ ÇÁ¸®¹Ì¾ö »ç¿ë') ON CONFLICT (i_num) DO NOTHING;
INSERT INTO quest_menu (i_num, str_menu) VALUES (45343, 'Coin Event Item Exchange') ON CONFLICT (i_num) DO NOTHING;
INSERT INTO quest_menu (i_num, str_menu) VALUES (45344, 'New server open event') ON CONFLICT (i_num) DO NOTHING;
INSERT INTO quest_menu (i_num, str_menu) VALUES (45345, 'Giant Top Lucky Pouch') ON CONFLICT (i_num) DO NOTHING;
INSERT INTO quest_menu (i_num, str_menu) VALUES (45346, 'Exchange Spirit Talisman') ON CONFLICT (i_num) DO NOTHING;
INSERT INTO quest_menu (i_num, str_menu) VALUES (45347, 'Purchase Talisman Upgrade Scroll') ON CONFLICT (i_num) DO NOTHING;
INSERT INTO quest_menu (i_num, str_menu) VALUES (45348, 'Exchange Talisman') ON CONFLICT (i_num) DO NOTHING;
INSERT INTO quest_menu (i_num, str_menu) VALUES (45349, 'Exchange Talisman of Courage') ON CONFLICT (i_num) DO NOTHING;
INSERT INTO quest_menu (i_num, str_menu) VALUES (45350, 'Purchase Spirit Talisman Fragment') ON CONFLICT (i_num) DO NOTHING;
INSERT INTO quest_menu (i_num, str_menu) VALUES (45351, 'Purchase with Noah') ON CONFLICT (i_num) DO NOTHING;
INSERT INTO quest_menu (i_num, str_menu) VALUES (45352, 'Armor of Destruction') ON CONFLICT (i_num) DO NOTHING;
INSERT INTO quest_menu (i_num, str_menu) VALUES (45353, 'Goblin Armor') ON CONFLICT (i_num) DO NOTHING;
INSERT INTO quest_menu (i_num, str_menu) VALUES (45354, '(+1) Wing Weapon Box exchange') ON CONFLICT (i_num) DO NOTHING;
INSERT INTO quest_menu (i_num, str_menu) VALUES (45355, 'vip ¹«±â ±³È¯±Ç') ON CONFLICT (i_num) DO NOTHING;
INSERT INTO quest_menu (i_num, str_menu) VALUES (45356, '30 - VIP Vault Key (7 Days)') ON CONFLICT (i_num) DO NOTHING;
INSERT INTO quest_menu (i_num, str_menu) VALUES (45357, '50 - Solar Pendant') ON CONFLICT (i_num) DO NOTHING;
INSERT INTO quest_menu (i_num, str_menu) VALUES (45358, 'Server Merge Event') ON CONFLICT (i_num) DO NOTHING;
INSERT INTO quest_menu (i_num, str_menu) VALUES (45359, '300 - <Solar Messenger> Achievement') ON CONFLICT (i_num) DO NOTHING;
INSERT INTO quest_menu (i_num, str_menu) VALUES (45360, 'ÇÁ¸®¹Ì¾ö 15ÀÏ') ON CONFLICT (i_num) DO NOTHING;
INSERT INTO quest_menu (i_num, str_menu) VALUES (45361, 'Near Bellua Village') ON CONFLICT (i_num) DO NOTHING;
INSERT INTO quest_menu (i_num, str_menu) VALUES (45362, 'Near Linart Village') ON CONFLICT (i_num) DO NOTHING;
INSERT INTO quest_menu (i_num, str_menu) VALUES (45363, 'Near the Forecourt of Luferson Castle') ON CONFLICT (i_num) DO NOTHING;
INSERT INTO quest_menu (i_num, str_menu) VALUES (45364, 'Near Laiba Village') ON CONFLICT (i_num) DO NOTHING;
INSERT INTO quest_menu (i_num, str_menu) VALUES (45365, 'Near Asga Village') ON CONFLICT (i_num) DO NOTHING;
INSERT INTO quest_menu (i_num, str_menu) VALUES (45366, 'Near the Forecourt of Elmorad Castle') ON CONFLICT (i_num) DO NOTHING;
INSERT INTO quest_menu (i_num, str_menu) VALUES (45367, '2nd Fort') ON CONFLICT (i_num) DO NOTHING;
INSERT INTO quest_menu (i_num, str_menu) VALUES (45368, '1st Fort') ON CONFLICT (i_num) DO NOTHING;
INSERT INTO quest_menu (i_num, str_menu) VALUES (45369, 'Luna Castle') ON CONFLICT (i_num) DO NOTHING;
INSERT INTO quest_menu (i_num, str_menu) VALUES (45370, 'Near the Guard Tower') ON CONFLICT (i_num) DO NOTHING;
INSERT INTO quest_menu (i_num, str_menu) VALUES (45371, 'Nereids Central Area') ON CONFLICT (i_num) DO NOTHING;
INSERT INTO quest_menu (i_num, str_menu) VALUES (45372, 'Front Yard') ON CONFLICT (i_num) DO NOTHING;
INSERT INTO quest_menu (i_num, str_menu) VALUES (45373, 'Near the Center') ON CONFLICT (i_num) DO NOTHING;
INSERT INTO quest_menu (i_num, str_menu) VALUES (45374, 'Beautiful Woman''s Help Request') ON CONFLICT (i_num) DO NOTHING;
INSERT INTO quest_menu (i_num, str_menu) VALUES (45375, 'Blessings of a Beautiful Lover') ON CONFLICT (i_num) DO NOTHING;
INSERT INTO quest_menu (i_num, str_menu) VALUES (45376, 'Draw Talisman of Courage') ON CONFLICT (i_num) DO NOTHING;
INSERT INTO quest_menu (i_num, str_menu) VALUES (45377, 'Purchase Resurrection Scroll 100%') ON CONFLICT (i_num) DO NOTHING;
INSERT INTO quest_menu (i_num, str_menu) VALUES (45378, 'Aset''s Unique Monster Staff') ON CONFLICT (i_num) DO NOTHING;
INSERT INTO quest_menu (i_num, str_menu) VALUES (45379, 'Play Knight online') ON CONFLICT (i_num) DO NOTHING;
INSERT INTO quest_menu (i_num, str_menu) VALUES (45380, 'Growing Seedlings') ON CONFLICT (i_num) DO NOTHING;
INSERT INTO quest_menu (i_num, str_menu) VALUES (45381, 'I will continue playing knight online') ON CONFLICT (i_num) DO NOTHING;
INSERT INTO quest_menu (i_num, str_menu) VALUES (45382, 'Hero''s Vow Exchange') ON CONFLICT (i_num) DO NOTHING;
INSERT INTO quest_menu (i_num, str_menu) VALUES (45383, '650 count - Lunar War Belt') ON CONFLICT (i_num) DO NOTHING;
INSERT INTO quest_menu (i_num, str_menu) VALUES (45384, '5 count - Open Lunar Chest') ON CONFLICT (i_num) DO NOTHING;
INSERT INTO quest_menu (i_num, str_menu) VALUES (45385, 'Purchase Ruler of the Legends Box') ON CONFLICT (i_num) DO NOTHING;
INSERT INTO quest_menu (i_num, str_menu) VALUES (45386, 'Open Ruler of the Legends Box') ON CONFLICT (i_num) DO NOTHING;
INSERT INTO quest_menu (i_num, str_menu) VALUES (45387, 'Use Lucky Emblem Voucher') ON CONFLICT (i_num) DO NOTHING;
INSERT INTO quest_menu (i_num, str_menu) VALUES (45388, '54ÀÌº¥Æ® ±â³ä') ON CONFLICT (i_num) DO NOTHING;
INSERT INTO quest_menu (i_num, str_menu) VALUES (45389, '54ÀÌº¥Æ® ±â³ä') ON CONFLICT (i_num) DO NOTHING;
INSERT INTO quest_menu (i_num, str_menu) VALUES (45390, 'Draw Talisman of Spirit') ON CONFLICT (i_num) DO NOTHING;
INSERT INTO quest_menu (i_num, str_menu) VALUES (45391, 'Purchase Garges Box ') ON CONFLICT (i_num) DO NOTHING;
INSERT INTO quest_menu (i_num, str_menu) VALUES (45392, 'Open Garges Box') ON CONFLICT (i_num) DO NOTHING;
INSERT INTO quest_menu (i_num, str_menu) VALUES (45393, 'Purchase Rosetta Armor Box') ON CONFLICT (i_num) DO NOTHING;
INSERT INTO quest_menu (i_num, str_menu) VALUES (45394, 'Open Rosetta Armor Box') ON CONFLICT (i_num) DO NOTHING;
INSERT INTO quest_menu (i_num, str_menu) VALUES (45395, 'Rosetta Armor Exchange') ON CONFLICT (i_num) DO NOTHING;
INSERT INTO quest_menu (i_num, str_menu) VALUES (45396, '[Character Daily] Defeat the Elite Pirates') ON CONFLICT (i_num) DO NOTHING;
INSERT INTO quest_menu (i_num, str_menu) VALUES (45397, 'Castle Siege Raffle Application') ON CONFLICT (i_num) DO NOTHING;
INSERT INTO quest_menu (i_num, str_menu) VALUES (45398, 'Box Purchase or Open') ON CONFLICT (i_num) DO NOTHING;
INSERT INTO quest_menu (i_num, str_menu) VALUES (45399, '½Å¼­¹ö ¿ÀÇÂ ±â³ä ¾ÆÀÌÅÛ Áö±Ş') ON CONFLICT (i_num) DO NOTHING;
INSERT INTO quest_menu (i_num, str_menu) VALUES (45400, '[Limited] Purchase Nereids') ON CONFLICT (i_num) DO NOTHING;
INSERT INTO quest_menu (i_num, str_menu) VALUES (45401, '[Limited] Waking up Nereids (Defense)') ON CONFLICT (i_num) DO NOTHING;
INSERT INTO quest_menu (i_num, str_menu) VALUES (45402, '[Cash] Waking up Nereids') ON CONFLICT (i_num) DO NOTHING;
INSERT INTO quest_menu (i_num, str_menu) VALUES (45403, 'Special Nereids (Defense) Exchange') ON CONFLICT (i_num) DO NOTHING;
INSERT INTO quest_menu (i_num, str_menu) VALUES (45404, 'Special Nereids (Attack) Exchange') ON CONFLICT (i_num) DO NOTHING;
INSERT INTO quest_menu (i_num, str_menu) VALUES (45405, '[Limited Edition] STR Increase Scroll (Large) Exchange') ON CONFLICT (i_num) DO NOTHING;
INSERT INTO quest_menu (i_num, str_menu) VALUES (45406, '[Limited Edition] HP Increase Scroll (Large) Exchange') ON CONFLICT (i_num) DO NOTHING;
INSERT INTO quest_menu (i_num, str_menu) VALUES (45407, '[Limited Edition] DEX Increase Scroll (Large) Exchange') ON CONFLICT (i_num) DO NOTHING;
INSERT INTO quest_menu (i_num, str_menu) VALUES (45408, '[Limited Edition] INT Increase Scroll (Large) Exchange') ON CONFLICT (i_num) DO NOTHING;
INSERT INTO quest_menu (i_num, str_menu) VALUES (45409, '[Limited Edition] MP Increase Scroll (Large) Exchange') ON CONFLICT (i_num) DO NOTHING;
INSERT INTO quest_menu (i_num, str_menu) VALUES (45410, '[Limited Edition] Lion''s Power Scroll (Large) Exchange') ON CONFLICT (i_num) DO NOTHING;
INSERT INTO quest_menu (i_num, str_menu) VALUES (45411, '[Limited] Waking up Nereids (Attack)') ON CONFLICT (i_num) DO NOTHING;
INSERT INTO quest_menu (i_num, str_menu) VALUES (45412, '[Limited] Stats Scroll') ON CONFLICT (i_num) DO NOTHING;
INSERT INTO quest_menu (i_num, str_menu) VALUES (45413, 'Special Nereids (Defense) - Non-tradable Exchange') ON CONFLICT (i_num) DO NOTHING;
INSERT INTO quest_menu (i_num, str_menu) VALUES (45414, 'Special Nereids (Attack) - Non-tradable Exchange') ON CONFLICT (i_num) DO NOTHING;
INSERT INTO quest_menu (i_num, str_menu) VALUES (45415, 'Special Nereids (Defense) - tradable Exchange') ON CONFLICT (i_num) DO NOTHING;
INSERT INTO quest_menu (i_num, str_menu) VALUES (45416, 'Special Nereids (Attack) - tradable Exchange') ON CONFLICT (i_num) DO NOTHING;
INSERT INTO quest_menu (i_num, str_menu) VALUES (45417, 'Character Delete') ON CONFLICT (i_num) DO NOTHING;
INSERT INTO quest_menu (i_num, str_menu) VALUES (45418, 'Character Delete and Character Restore') ON CONFLICT (i_num) DO NOTHING;
INSERT INTO quest_menu (i_num, str_menu) VALUES (45419, 'Trade [Trophy of High Class Flame]') ON CONFLICT (i_num) DO NOTHING;
INSERT INTO quest_menu (i_num, str_menu) VALUES (45420, '¸ó½ºÅÍ ½ºÅÂÇÁ 1°³ ±³È¯') ON CONFLICT (i_num) DO NOTHING;
INSERT INTO quest_menu (i_num, str_menu) VALUES (45421, '¸ó½ºÅÍ ½ºÅÂÇÁ 5°³ ±³È¯') ON CONFLICT (i_num) DO NOTHING;
INSERT INTO quest_menu (i_num, str_menu) VALUES (45422, '¸ó½ºÅÍ ½ºÅÂÇÁ 10°³ ±³È¯') ON CONFLICT (i_num) DO NOTHING;
INSERT INTO quest_menu (i_num, str_menu) VALUES (45423, 'Event Oreads Exchange Ticket (7 days)') ON CONFLICT (i_num) DO NOTHING;
INSERT INTO quest_menu (i_num, str_menu) VALUES (45424, 'Blessed Talisman Untradeable Exchange') ON CONFLICT (i_num) DO NOTHING;
INSERT INTO quest_menu (i_num, str_menu) VALUES (45425, 'Register for Quest Reset Event') ON CONFLICT (i_num) DO NOTHING;
INSERT INTO quest_menu (i_num, str_menu) VALUES (45426, 'Equipment Confirmation Item ') ON CONFLICT (i_num) DO NOTHING;
INSERT INTO quest_menu (i_num, str_menu) VALUES (45427, '[2024 Exclusive Achievement] Enter Juraid') ON CONFLICT (i_num) DO NOTHING;
INSERT INTO quest_menu (i_num, str_menu) VALUES (45436, '200°³ -  ¾ğ´õ´õÄ³½½ ¹«±â ±³È¯±Ç') ON CONFLICT (i_num) DO NOTHING;
INSERT INTO quest_menu (i_num, str_menu) VALUES (45447, '[Knight Online 20th Anniversary Emblem] Exchange') ON CONFLICT (i_num) DO NOTHING;
INSERT INTO quest_menu (i_num, str_menu) VALUES (45449, '[Knight Online 20th Anniversary Emblem] Exchange(3days)') ON CONFLICT (i_num) DO NOTHING;
INSERT INTO quest_menu (i_num, str_menu) VALUES (45450, '[Knight Online 20th Anniversary Emblem] Exchange(7days)') ON CONFLICT (i_num) DO NOTHING;
INSERT INTO quest_menu (i_num, str_menu) VALUES (45492, '200°³ - [°­Ã¶»çÀÚ] ¹æÆĞ ') ON CONFLICT (i_num) DO NOTHING;
INSERT INTO quest_menu (i_num, str_menu) VALUES (45493, '200°³ - [°­Ã¶»çÀÚ] ÀÚ¸¶´Ù¸£ ') ON CONFLICT (i_num) DO NOTHING;
INSERT INTO quest_menu (i_num, str_menu) VALUES (45494, '200°³ - [°­Ã¶»çÀÚ] ¹«±â') ON CONFLICT (i_num) DO NOTHING;
INSERT INTO quest_menu (i_num, str_menu) VALUES (45495, '±³È¯±Ç ¾ÆÀÌÅÛ ±³È¯') ON CONFLICT (i_num) DO NOTHING;
INSERT INTO quest_menu (i_num, str_menu) VALUES (45528, 'È¯¼öÀÇ ÁÖÀÎ - À¯´ÏÄÜ(ûı)') ON CONFLICT (i_num) DO NOTHING;
INSERT INTO quest_menu (i_num, str_menu) VALUES (45531, 'È¯¼öÀÇ ÁÖÀÎ - µğ¾Æ³ªÀÇ»ç½¿') ON CONFLICT (i_num) DO NOTHING;
INSERT INTO quest_menu (i_num, str_menu) VALUES (45536, 'Wing of Steel Nation Point (Restrictions apply) +3 Purchase') ON CONFLICT (i_num) DO NOTHING;
INSERT INTO quest_menu (i_num, str_menu) VALUES (45537, 'Wing of Assassin - HP 300') ON CONFLICT (i_num) DO NOTHING;
INSERT INTO quest_menu (i_num, str_menu) VALUES (45538, 'Wing of Pitch Black - Defense Power +50') ON CONFLICT (i_num) DO NOTHING;
INSERT INTO quest_menu (i_num, str_menu) VALUES (45539, 'Wing of Darkness Nation Point (Restrictions apply) +3 Purchase') ON CONFLICT (i_num) DO NOTHING;
INSERT INTO quest_menu (i_num, str_menu) VALUES (45540, 'Wing of Darkness - Defense Power +50') ON CONFLICT (i_num) DO NOTHING;
INSERT INTO quest_menu (i_num, str_menu) VALUES (45541, 'Wing of Darkness - HP 300') ON CONFLICT (i_num) DO NOTHING;
INSERT INTO quest_menu (i_num, str_menu) VALUES (45542, 'Purchase Warrior¡¯s Wings (Base Experience for Monster Kills +9%)') ON CONFLICT (i_num) DO NOTHING;
INSERT INTO quest_menu (i_num, str_menu) VALUES (45561, '250°³ - [Èæ»çÀÚ] È°') ON CONFLICT (i_num) DO NOTHING;
INSERT INTO quest_menu (i_num, str_menu) VALUES (45564, '250°³ - [Èæ»çÀÚ] ¹«±â') ON CONFLICT (i_num) DO NOTHING;
INSERT INTO quest_menu (i_num, str_menu) VALUES (45565, '250°³ - [Èæ»çÀÚ] ÀÚ¸¶´Ù¸£') ON CONFLICT (i_num) DO NOTHING;
INSERT INTO quest_menu (i_num, str_menu) VALUES (45566, 'Special Oreads Voucher - Untradable Exchange') ON CONFLICT (i_num) DO NOTHING;
INSERT INTO quest_menu (i_num, str_menu) VALUES (45567, 'Special Oreads Voucher (1 day) - Untradable') ON CONFLICT (i_num) DO NOTHING;
INSERT INTO quest_menu (i_num, str_menu) VALUES (45568, 'Special Oreads Voucher (3 day) - Untradable') ON CONFLICT (i_num) DO NOTHING;
INSERT INTO quest_menu (i_num, str_menu) VALUES (45569, 'Special Oreads Voucher (7 day) - Untradable') ON CONFLICT (i_num) DO NOTHING;
INSERT INTO quest_menu (i_num, str_menu) VALUES (45570, 'Special Oreads Voucher (15 day) - Untradable') ON CONFLICT (i_num) DO NOTHING;
INSERT INTO quest_menu (i_num, str_menu) VALUES (45571, 'Special Oreads (Attack) (7 day) - Untradable') ON CONFLICT (i_num) DO NOTHING;
INSERT INTO quest_menu (i_num, str_menu) VALUES (45572, 'Special Oreads (Defense) (7 day) - Untradable') ON CONFLICT (i_num) DO NOTHING;
INSERT INTO quest_menu (i_num, str_menu) VALUES (45573, 'Ticket Exchange Use') ON CONFLICT (i_num) DO NOTHING;
INSERT INTO quest_menu (i_num, str_menu) VALUES (45574, 'º¹ÁÖ¸Ó´Ï ¹× °ñµå µå·¡°ï »óÀÚ ±³È¯') ON CONFLICT (i_num) DO NOTHING;
INSERT INTO quest_menu (i_num, str_menu) VALUES (45575, 'Anniversary Event: Free Wing Giveaway') ON CONFLICT (i_num) DO NOTHING;
INSERT INTO quest_menu (i_num, str_menu) VALUES (45576, '[¾ğ´õ ´õ Ä³½½ Àü¸®Ç°] ±³È¯') ON CONFLICT (i_num) DO NOTHING;
INSERT INTO quest_menu (i_num, str_menu) VALUES (45577, '250°³ - È­·æÀÇ ¹İÁö(+1)') ON CONFLICT (i_num) DO NOTHING;
INSERT INTO quest_menu (i_num, str_menu) VALUES (45578, 'È²Á¦ÀÇ ÈÆÀåÀ» ¿øÇÕ´Ï´Ù.') ON CONFLICT (i_num) DO NOTHING;
INSERT INTO quest_menu (i_num, str_menu) VALUES (45579, '[General Sales Item List]') ON CONFLICT (i_num) DO NOTHING;
INSERT INTO quest_menu (i_num, str_menu) VALUES (45580, 'War Hero Wings (30 Days) - 120 M Noah') ON CONFLICT (i_num) DO NOTHING;
INSERT INTO quest_menu (i_num, str_menu) VALUES (45581, 'Lunar Tattoo (30 Days) - 160 M Noah') ON CONFLICT (i_num) DO NOTHING;
INSERT INTO quest_menu (i_num, str_menu) VALUES (45582, 'User Buff Pet Scroll - HP 200 - 65M') ON CONFLICT (i_num) DO NOTHING;
INSERT INTO quest_menu (i_num, str_menu) VALUES (45583, 'User Buff Pet Scroll - AC 20 - 65M') ON CONFLICT (i_num) DO NOTHING;
INSERT INTO quest_menu (i_num, str_menu) VALUES (45584, 'User Buff Pet Scroll - Atk 5 - 78M') ON CONFLICT (i_num) DO NOTHING;
INSERT INTO quest_menu (i_num, str_menu) VALUES (45585, '»óÀÚ ±³È¯') ON CONFLICT (i_num) DO NOTHING;
INSERT INTO quest_menu (i_num, str_menu) VALUES (45586, '400°³ - +8 Ãàº¹ ÁÖ¹®¼­') ON CONFLICT (i_num) DO NOTHING;
INSERT INTO quest_menu (i_num, str_menu) VALUES (45587, 'Mask of the Evil Spirit') ON CONFLICT (i_num) DO NOTHING;
INSERT INTO quest_menu (i_num, str_menu) VALUES (45588, 'Ä³½¬ ¼Ò¸ğ ¾ÆÀÌÅÛ ±³È¯') ON CONFLICT (i_num) DO NOTHING;
INSERT INTO quest_menu (i_num, str_menu) VALUES (45589, 'È®·üÇü ¾ÆÀÌÅÛ ±³È¯') ON CONFLICT (i_num) DO NOTHING;
INSERT INTO quest_menu (i_num, str_menu) VALUES (45590, 'ÇÁ¸®¹Ì¾ö Áö±Ş ¾ÆÀÌÅÛ ±³È¯') ON CONFLICT (i_num) DO NOTHING;
INSERT INTO quest_menu (i_num, str_menu) VALUES (45591, 'Àå½Ä ¿¥ºí·³ ¹× ÄªÈ£ ±³È¯') ON CONFLICT (i_num) DO NOTHING;
INSERT INTO quest_menu (i_num, str_menu) VALUES (45592, '¹«±â ¹× ¹æ¾î±¸ ±³È¯') ON CONFLICT (i_num) DO NOTHING;
INSERT INTO quest_menu (i_num, str_menu) VALUES (45593, '50°³ - ½ÅÁßÀÇ Å»¸®½º¸¸(+5)') ON CONFLICT (i_num) DO NOTHING;
INSERT INTO quest_menu (i_num, str_menu) VALUES (45594, '200°³ - µå¶óÅ° ¸ñ°ÉÀÌ s±Ş ´ÜÀÏ') ON CONFLICT (i_num) DO NOTHING;
INSERT INTO quest_menu (i_num, str_menu) VALUES (45595, '200°³ - ÈûÀÇ µå¶óÅ°ÀÇ Ææ´øÆ® V') ON CONFLICT (i_num) DO NOTHING;
INSERT INTO quest_menu (i_num, str_menu) VALUES (45596, '200°³ - ¹ÎÃ¸ÀÇ µå¶óÅ°ÀÇ Ææ´øÆ® V') ON CONFLICT (i_num) DO NOTHING;
INSERT INTO quest_menu (i_num, str_menu) VALUES (45597, '200°³ - Áö·ÂÀÇ µå¶óÅ°ÀÇ Ææ´øÆ® V') ON CONFLICT (i_num) DO NOTHING;
INSERT INTO quest_menu (i_num, str_menu) VALUES (45598, '200°³ - ¸¶·ÂÀÇ µå¶óÅ°ÀÇ Ææ´øÆ® V') ON CONFLICT (i_num) DO NOTHING;
INSERT INTO quest_menu (i_num, str_menu) VALUES (45599, '200°³ - ÇöÀÚÀÇ µå¶óÅ°ÀÇ Ææ´øÆ® V') ON CONFLICT (i_num) DO NOTHING;
INSERT INTO quest_menu (i_num, str_menu) VALUES (45600, '[Èæ»çÀÚ] ´ë°Å ') ON CONFLICT (i_num) DO NOTHING;
INSERT INTO quest_menu (i_num, str_menu) VALUES (45601, '[Èæ»çÀÚ] ¾×½º') ON CONFLICT (i_num) DO NOTHING;
INSERT INTO quest_menu (i_num, str_menu) VALUES (45602, '[Èæ»çÀÚ] ÀåÃ¢') ON CONFLICT (i_num) DO NOTHING;
INSERT INTO quest_menu (i_num, str_menu) VALUES (45603, '[Èæ»çÀÚ] È­¿°ÀÇ ÁöÆÎÀÌ ') ON CONFLICT (i_num) DO NOTHING;
INSERT INTO quest_menu (i_num, str_menu) VALUES (45604, '[Èæ»çÀÚ] ³Ã±âÀÇ ÁöÆÎÀÌ ') ON CONFLICT (i_num) DO NOTHING;
INSERT INTO quest_menu (i_num, str_menu) VALUES (45605, '[Èæ»çÀÚ] Àü°İÀÇ ÁöÆÎÀÌ ') ON CONFLICT (i_num) DO NOTHING;
INSERT INTO quest_menu (i_num, str_menu) VALUES (45606, '[Èæ»çÀÚ] È°') ON CONFLICT (i_num) DO NOTHING;
INSERT INTO quest_menu (i_num, str_menu) VALUES (45607, '[Èæ»çÀÚ] ¹æÆĞ ') ON CONFLICT (i_num) DO NOTHING;
INSERT INTO quest_menu (i_num, str_menu) VALUES (45608, '[Èæ»çÀÚ] ¸ŞÀÌ½º') ON CONFLICT (i_num) DO NOTHING;
INSERT INTO quest_menu (i_num, str_menu) VALUES (45609, '[Èæ»çÀÚ] ÀÚ¸¶´Ù¸£') ON CONFLICT (i_num) DO NOTHING;
INSERT INTO quest_menu (i_num, str_menu) VALUES (45610, '[Èæ»çÀÚ] ¹«±â') ON CONFLICT (i_num) DO NOTHING;
INSERT INTO quest_menu (i_num, str_menu) VALUES (45611, '½ºÆä¼È ¿À·¹¾Æµå½º(°ø°İÇü) (7ÀÏ) - °Å·¡°¡´É') ON CONFLICT (i_num) DO NOTHING;
INSERT INTO quest_menu (i_num, str_menu) VALUES (45612, '½ºÆä¼È ¿À·¹¾Æµå½º(¹æ¾îÇü) (7ÀÏ) - °Å·¡°¡´É') ON CONFLICT (i_num) DO NOTHING;
INSERT INTO quest_menu (i_num, str_menu) VALUES (45613, 'Special Oreads Voucher (7 day)') ON CONFLICT (i_num) DO NOTHING;
INSERT INTO quest_menu (i_num, str_menu) VALUES (45614, 'Á×ÀºÀÚÀÇ °Ë ±¸¸Å') ON CONFLICT (i_num) DO NOTHING;
INSERT INTO quest_menu (i_num, str_menu) VALUES (45615, 'È²±İ ½ºÀ§Äª ÇÁ¸®¹Ì¾ö ±³È¯') ON CONFLICT (i_num) DO NOTHING;
INSERT INTO quest_menu (i_num, str_menu) VALUES (45616, 'Magic Warehouse Ticket (100 pieces)') ON CONFLICT (i_num) DO NOTHING;
INSERT INTO quest_menu (i_num, str_menu) VALUES (45617, '½ºÆä¼È ¿À·¹¾Æµå½º(°ø°İÇü)') ON CONFLICT (i_num) DO NOTHING;
INSERT INTO quest_menu (i_num, str_menu) VALUES (45618, '½ºÆä¼È ¿À·¹¾Æµå½º(¹æ¾îÇü)') ON CONFLICT (i_num) DO NOTHING;
INSERT INTO quest_menu (i_num, str_menu) VALUES (48067, '[Exchange] Portu Armor') ON CONFLICT (i_num) DO NOTHING;
